libremesh/lime-packages

packages/lime-system/files/etc/config/lime
packages/lime-system/files/etc/config/lime-defaults

I added some comments in Libre-Mesh configuration files.

Added comments in configuration files

---

packages/lime-proto-olsr/Makefile
packages/lime-proto-olsr/src/olsr.lua
packages/lime-proto-olsr6/Makefile
packages/lime-proto-olsr6/src/olsr6.lua

Adds support to OLSR v1 routing protocol.
IPv4 and IPv6 version are separated.

OLSR v1 proto support

---

README.md

I corrected an URL; I added some text taken from the website for clarifying what's this repository for; I added some instructions for manual compilation.

Changes on Readme file

---

packages/lime-hwd-ground-routing/Makefile
packages/lime-system/files/etc/config/lime

I added the description for lime-hwd-ground-routing package and added comments in /etc/config/lime file in ground routing section.

Added comments and description for ground routing package

---

README.md

This solves #45. A similar issue should be filed also for lime-build repository.

Added contact informations to readme

---

packages/bmx6-auto-gw-mode/Makefile
packages/bmx7-auto-gw-mode/Makefile
packages/bmx7-auto-gw-mode/files/etc/watchping/wan-fail.d/bmx7-gw
packages/bmx7-auto-gw-mode/files/etc/watchping/wan-ok.d/bmx7-gw
packages/lime-proto-bmx6/Makefile
packages/lime-proto-bmx6/src/bmx6.lua
packages/lime-proto-bmx7/Makefile
packages/lime-proto-bmx7/src/bmx7.lua

cleaned the bmx6/bmx7 mixup. bmx7 part untestet because i have not enough 8mb devices.

Bmx6 & bmx7 cleaning

---

packages/lime-freifunk/files/lime-freifunk.defaults
packages/lime-system/files/usr/lib/lua/lime/wireless.lua

10km is a bit to extreme and leads to duplicate packets...

customize distance setting

---

packages/luci-mod-status/files/usr/lib/lua/luci/view/status/index.htm

its just a copy of the original luci status index view

updated index view of luci-mod-status

---

packages/lime-system/files/etc/lime/rc.d/apply-eb-ip-rules-if-not-fw.sh

another try to pullrequest my fix for #57

Firewall.user.d fix

---

packages/lime-system/files/usr/lib/lua/lime/network.lua

Fix fix invalid network.primary_address

---

packages/lime-system/files/etc/config/lime-example

Update lime-example, rewrite of #67

Update lime-example, rewrite of #67

---

packages/lime-webui/Makefile
packages/lime-webui/luasrc/controller/lime.lua
packages/lime-webui/luasrc/model/notes.lua
packages/lime-webui/src/etc/profile.d/system_notes.sh

Adds system notes to lime.

---

packages/lime-webui/luasrc/controller/lime.lua
packages/lime-webui/luasrc/view/applyreboot.htm
packages/lime-webui/luasrc/view/flashops.htm
packages/lime-webui/luasrc/view/sysupgrade.htm
packages/lime-webui/luasrc/view/upgrade.htm

This pull request adds the functionality of SysUpgrade on LiMe.
Uses the new lime-sysupgrade instead of the LEDE's one.

Migrating SysUpgrade functionality to LiMe

---

packages/lime-system/files/etc/config/lime-defaults

Discussed in the mailing list.

Change default WiFi mode to ieee80211s (instead of adhoc)

---

packages/lime-basic/Makefile

Fix lime-basic Makefile

---

README.md

Update README information for upcoming 17.06 release

---

packages/smonit/files/etc/uci-defaults/99_smonit
packages/smonit/files/usr/sbin/smonit

- Enables smonit on first boot
- Improve log size cleanup strategy

Small improvements on smonit

---

CONTRIBUTING.md

@ilario, do you think that more information is needed on how to test the packages or the system of continuous integration?

Add how to contribute guide

---

.travis.yml

Based on https://github.com/probonopd/announce/blob/master/.travis.yml

Implementing Contiuous Integration

---

packages/lime-system/files/etc/config/lime-defaults
packages/lime-webui/luasrc/model/essentials.lua
packages/lime-webui/po/es/lime-webui.po

Set default WiFi distane to 1000. Add webui option to set distance

---

packages/lime-webui/Makefile
packages/lime-webui/clean_i18n.sh

Adds translation cleaning after build

---

packages/lime-system/Makefile
packages/lime-system/files/usr/lib/lua/lime/wireless.lua

Use libiwinfo-lua do detect radio mode instead of uci

---

LICENSE

Add AGPLv3 license file as default license for all libremesh code

---

packages/lime-system/files/usr/lib/lua/lime/config.lua

This was the cause of openwrt_wan being broken on checking if the config
section was autogenerable

Fix config.set behaviour with uhandled types

---

packages/smonit/files/etc/init.d/smonit

smonit: hotfix bashisms

---

packages/lime-full/Makefile

Enables lime-app as default package on lime-full

---

packages/dnsmasq-lease-share/Makefile
packages/dnsmasq-lease-share/files/etc/uci-defaults/90_dnsmasq-lease-share
packages/dnsmasq-lease-share/src/dnsmasq-lease-share.sh

Fix #276 dnsmasq lease share script

---

packages/dnsmasq-lease-share/Makefile

dnsmasq-lease-share: create (missing) /usr/bin directory

---

packages/lime-proto-bmx7/src/bmx7.lua
packages/lime-system/files/etc/config/lime-defaults

Follows bmx6 changes.
Still not tested in a real, production node. Waiting for comments...

lime-proto-bmx7: update script and options

---

packages/lime-proto-bmx7/src/bmx7.lua

Set correct values for firewall.

lime-proto-bmx7: update protocol script

---

packages/cotonete/Makefile
packages/cotonete/files/etc/init.d/cotonete
packages/cotonete/files/usr/sbin/cotonete.sh

Cotonete comes to replace deaf_phys by a better approach, as a daemon.

Adds cotonete to repo.

---

packages/lime-system/files/usr/bin/lime-apply

lime-system: include bmx7 to lime-apply

---

packages/lime-system/files/usr/lib/lua/lime/wireless.lua

fix error due to local ignored freqs if 2.4ghz

wireless: fix ignored freqs + default htmode

---

packages/lime-proto-bmx6/src/bmx6.lua
packages/lime-proto-bmx7/src/bmx7.lua

thanks @dangowrt for reporting

lime-proto-bmx{6,7}: fix typo

---

packages/lime-proto-bmx6/src/bmx6.lua
packages/lime-proto-bmx7/src/bmx7.lua
packages/lime-system/files/etc/config/lime-defaults

lime-proto-bmx{6,7}: add bmxN_wifi_max_rate option

---

packages/lime-smart-wifi/Makefile
packages/lime-smart-wifi/files/etc/uci-defaults/90_lime-smart-wifi
packages/lime-smart-wifi/src/lime-smart-wifi.lua

lime-smart-wifi: only apname if defined in modes

---

packages/lime-webui/po/de/lime-webui.po
packages/lime-webui/po/el/lime-webui.po
packages/lime-webui/po/es/lime-webui.po
packages/lime-webui/po/fi/lime-webui.po
packages/lime-webui/po/fr/lime-webui.po
packages/lime-webui/po/it/lime-webui.po
packages/lime-webui/po/ko/lime-webui.po
packages/lime-webui/po/lb/lime-webui.po
packages/lime-webui/po/pt-br/lime-webui.po
packages/lime-webui/po/pt/lime-webui.po
packages/lime-webui/po/qqq/lime-webui.po
packages/lime-webui/po/ru/lime-webui.po
packages/lime-webui/po/sv/lime-webui.po
packages/lime-webui/po/tr/lime-webui.po
packages/lime-webui/po/zh-hans/lime-webui.po
packages/lime-webui/po/zh-hant/lime-webui.po

New languages! Will they show up on the language selection menu for users in LuCI?

Localisation updates from https://translatewiki.net.

---

packages/lime-proto-bmx7/src/bmx7.lua

lime-proto-bmx7: add option to run on librenet6

---

packages/lime-proto-babeld/src/babeld.lua

make babeld run on librenet6 tinc interface

add option babeld_over_librenet6

---

packages/lime-webui/po/ast/lime-webui.po
packages/lime-webui/po/ca/lime-webui.po
packages/lime-webui/po/de/lime-webui.po
packages/lime-webui/po/el/lime-webui.po
packages/lime-webui/po/es/lime-webui.po
packages/lime-webui/po/fi/lime-webui.po
packages/lime-webui/po/fr/lime-webui.po
packages/lime-webui/po/it/lime-webui.po
packages/lime-webui/po/ko/lime-webui.po
packages/lime-webui/po/nb/lime-webui.po
packages/lime-webui/po/pt-br/lime-webui.po
packages/lime-webui/po/pt/lime-webui.po
packages/lime-webui/po/qqq/lime-webui.po
packages/lime-webui/po/ru/lime-webui.po
packages/lime-webui/po/sv/lime-webui.po
packages/lime-webui/po/tr/lime-webui.po
packages/lime-webui/po/zh-hans/lime-webui.po
packages/lime-webui/po/zh-hant/lime-webui.po

translationwiki.net translations up to 14 june 2018

Feature/tw translations - up to 14 june 2018

---

packages/lime-smart-wifi/src/lime-smart-wifi.lua

lime-smart-wifi: skip if wifi modes empty

---

packages/lime-system/files/etc/config/lime-defaults
packages/lime-system/files/usr/lib/lua/lime/board.sh
packages/lime-system/files/usr/lib/lua/lime/config.lua
packages/lime-system/files/usr/lib/lua/lime/network.lua

only return first found interface

board.sh: fixup multiple interfaces

---

packages/lime-librenet6/Makefile
packages/lime-librenet6/files/etc/tinc/librenet6/tinc-up
packages/lime-librenet6/files/etc/uci-defaults/tinc-setup

add lime-librenet6 package

---

packages/lime-system/files/usr/lib/lua/lime/wireless.lua

Move marcos patch to correct branch

Indicate to which radio we want to apply wireless modes

---

README.md
packages/lime-system/files/etc/uci-defaults/92_add-lime-repos

Change LEDE occurrences to OpenWrt

---

packages/smonit/files/etc/smonit/dnsmasq

smonit dnsmasq repeat quickfix as longfix

---

packages/lime-docs/files/lime-example

In #405 (merged) we add the ability to indicate to which type of radios we want to apply the wireless modes.
In this pull request I add that information to lime-example

Add documentation about pull/405

---

packages/lime-webui/po/ar/lime-webui.po
packages/lime-webui/po/ast/lime-webui.po
packages/lime-webui/po/ca/lime-webui.po
packages/lime-webui/po/da/lime-webui.po
packages/lime-webui/po/de/lime-webui.po
packages/lime-webui/po/el/lime-webui.po
packages/lime-webui/po/es/lime-webui.po
packages/lime-webui/po/eu/lime-webui.po
packages/lime-webui/po/fi/lime-webui.po
packages/lime-webui/po/fr/lime-webui.po
packages/lime-webui/po/it/lime-webui.po
packages/lime-webui/po/ko/lime-webui.po
packages/lime-webui/po/lb/lime-webui.po
packages/lime-webui/po/nb/lime-webui.po
packages/lime-webui/po/pt-br/lime-webui.po
packages/lime-webui/po/pt/lime-webui.po
packages/lime-webui/po/qqq/lime-webui.po
packages/lime-webui/po/ru/lime-webui.po
packages/lime-webui/po/sr-ec/lime-webui.po
packages/lime-webui/po/sv/lime-webui.po
packages/lime-webui/po/tr/lime-webui.po
packages/lime-webui/po/zh-hans/lime-webui.po
packages/lime-webui/po/zh-hant/lime-webui.po

posting to master branch because develop has disappeared. Not sure if this is the correct branch to submit the pull request to.

Translations from translatewiki.net

---

packages/lime-webui/luasrc/model/essentials.lua

If bmx6 not installed do not crash lime-webui

---

packages/lime-system/files/usr/lib/lua/lime/network.lua

IP like 10.0.0.1/24 should be possible as main address if anygw not installed nor enabled.

Allow use first IP of ipv4 range if anygw not enabled

---

packages/lime-proto-anygw/src/anygw.lua

proto-anygw filter rogue router advertisement

---

.github/stale.yml

Fix typos in stale bot configuration

Fix tags list

---

packages/lime-system/files/usr/bin/lime-config
packages/shared-state-bat_hosts/files/etc/uci-defaults/shared-state-bat_hosts-cron
packages/shared-state-date/files/etc/shared-state/hooks/date/set_date
packages/shared-state-date/files/etc/uci-defaults/shared-state-date-cron
packages/shared-state-dnsmasq_hosts/files/etc/uci-defaults/shared-state-dnsmasq_hosts-cron
packages/shared-state-dnsmasq_hosts/files/usr/bin/shared-state-generate_dnsmasq_hosts
packages/shared-state-dnsmasq_leases/files/etc/uci-defaults/90_dnsmasq-lease-share
packages/shared-state-dnsmasq_leases/files/usr/bin/dnsmasq-lease-share.sh
packages/shared-state-dnsmasq_leases/files/usr/bin/shared-state-generate_dnsmasq_leases
packages/shared-state-dnsmasq_leases/files/usr/bin/shared-state-publish_dnsmasq_leases
packages/shared-state/files/etc/uci-defaults/shared-state-publishers-cron
packages/shared-state/files/usr/bin/shared-state
packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
packages/shared-state/files/www/cgi-bin/shared-state

ignore interfaces which doesn't lead to own broadcast domain

shared-state finer neighbour chosing and multiple fixes

---

packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua

Change name/%H in favor of name.%H

Fix adhoc and mesh id in FBW

---

libremesh.sdk.config
packages/pirania/Makefile

we did, along with @luandro and @hiurequeiroz a major refactor of the iptables integration of pitbull and finally renamed it to pirania

Rename pitbull to pirania

---

packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard/functools.lua
packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard/utils.lua

These changes change the following behavior: 
- Before doing the scan sort the networks by type and channel. 
- At the moment of connecting it checks if the channel and mode is the same that is configured.
- If it is the same it avoids the configuration change
- If it is not the same make the necessary changes for the connection
Doing this saves a lot of time and improves the performance of the utility.
It also adds functions like reduce, flatTable, sortBy and splitBy to functools.

FBW preformance enhancements

---

packages/ubus-lime-metrics/files/etc/uci-defaults/99-save-last-known-path-to-internet
packages/ubus-lime-metrics/files/usr/libexec/rpcd/lime-metrics
packages/ubus-lime-metrics/files/usr/sbin/last_internet

Currently lime-ubus tools are tied to bmx6, this pull request adds support for babeld detecting which of the two protocols is installed.

Add babeld support to ubus-lime-metrics and last_internet_path

---

packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard/utils.lua
packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils

Add FWB support for 5ghz multi-radio devices, like LibreRouter (with two 5ghz radios).
Changes include filtering according to device mac addresses and improved performance.

[FBW] Add support for 5ghz multi-radio devices

---

packages/lime-app/Makefile

* **fbw:** get full config from networks found ([5304a69](https://github.com/libremesh/lime-app/commit/5304a69))
* **gui:** add option to toggleMenuButton ([725e5e9](https://github.com/libremesh/lime-app/commit/725e5e9))
* **typo:** fix most active hostname ([dc48770](https://github.com/libremesh/lime-app/commit/dc48770))
* **url:** disable redirect after connection ([3e1802a](https://github.com/libremesh/lime-app/commit/3e1802a))
* **url:** redirect if path is empty ([274d7dd](https://github.com/libremesh/lime-app/commit/274d7dd))
* **fbw:** hide menu button in FBW page ([2efa7c8](https://github.com/libremesh/lime-app/commit/2efa7c8))
* **gui:** handle menu button form redux ([276847a](https://github.com/libremesh/lime-app/commit/276847a))
* **gui:** hide menu button …

LimeApp updated to v0.2.0-alpha.11

---

packages/hotplug-initd-services/Makefile
packages/hotplug-initd-services/files/etc/init.d/hotplug-initd-observer
packages/hotplug-initd-services/files/etc/uci-defaults/hotplug-initd-services
packages/hotplug-initd-services/files/usr/bin/hotplug-initd-observer
packages/shared-state-babeld_hosts/Makefile
packages/shared-state-babeld_hosts/files/etc/babeld-hosts
packages/shared-state-babeld_hosts/files/etc/hotplug.d/initd/shared-state-babeld_hosts
packages/shared-state-babeld_hosts/files/etc/shared-state/hooks/babeld-hosts/shared-state-generate_babeld_hosts
packages/shared-state-babeld_hosts/files/etc/shared-state/publishers/shared-state-publish_babeld_hosts
packages/shared-state-babeld_hosts/files/etc/uci-defaults/shared-state-babeld_hosts-cron
packages/shared-state-babeld_hosts/files/usr/bin/bab2host
packages/shared-state-babeld_hosts/files/usr/bin/host2bab
packages/shared-state-babeld_hosts/files/usr/bin/shared-state-generate_babeld_hosts
packages/shared-state-babeld_hosts/files/usr/bin/shared-state-publish_babeld_hosts
packages/shared-state-dnsmasq_hosts/files/usr/bin/shared-state-generate_dnsmasq_hosts
packages/shared-state-dnsmasq_leases/Makefile
packages/shared-state-dnsmasq_leases/files/etc/uci-defaults/90_dnsmasq-lease-share
packages/shared-state-dnsmasq_leases/files/usr/bin/shared-state-generate_dnsmasq_leases
packages/shared-state-dnsmasq_leases/files/usr/bin/shared-state-publish_dnsmasq_leases
packages/shared-state/files/etc/uci-defaults/shared-state-publishers-cron
packages/shared-state/files/usr/bin/shared-state
packages/shared-state/files/usr/lib/lua/shared-state.lua
packages/shared-state/files/www/cgi-bin/shared-state

scrape /etc/dnsmasq.d/*.conf files looking for
`dhcp-host=MAC,IPv4,HOSTNAME,infinite`
lines and share those static leases too
Fix config file name in uci-defaults

Multiple improvements to shared-state

---

packages/lime-proto-anygw/src/anygw.lua

I tried doing this as a cname but for this to work thisnode.info must be also in /etc/hosts

add minodo.info dns entry (like thisnode.info)

---

packages/ubus-lime-metrics/files/usr/libexec/rpcd/lime-metrics
packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils

Get cloud nodes from /etc/bat-hosts instead of from bmx6 and fix some typo in get_gateway

Fix lime ubus

---

packages/ubus-lime-metrics/files/usr/sbin/last_internet

Fix json generation in last_intrernet

Fix typo in bash

---

packages/first-boot-wizard/files/bin/firstbootwizard
packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard/functools.lua
packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard/utils.lua
packages/first-boot-wizard/tests/test_firstbootwizard.lua
packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw

This changes allow unit testing fbw. The test is just a starting point.

First boot wizard refactor into module and test stub

---

libremesh.sdk.config

we forgot to remove the package from the config. this PR fixes that.

Removes cotonete from config.

---

packages/lime-app/Makefile

Improvements in relation to the previous version:
- Eliminated duplication of hosts in the configuration screen
- Navigate between nodes more clearly
- Validation in the FBW form

LimeApp updated to v0.2.0

---

README.md

Completed requested changes for #608

#608 Readme Build Removal

---

packages/lime-system/files/usr/lib/lua/lime/system.lua

* increase max_requests from 3 (default) to 6
* decrease script_timeout from 60s (default) to 15s

Improve uhttpd config

---

packages/lime-app/Makefile

This pull-request improves the user experience in firstbootwizard. Auto format the community network and node name at the time of setup

LimeApp updated to v0.2.1

---

TESTING.md
packages/first-boot-wizard/tests/test_firstbootwizard.lua
packages/lime-hwd-openwrt-wan/tests/test_lime_hwd_openwrt_wan.lua
packages/lime-system/files/usr/lib/lua/lime/utils.lua
packages/lime-system/tests/test_lime_network.lua
run_tests
tests/test_lime_config_device.lua

Use LUA_ENABLE_LOGGING to send utils.log to stdout

testing: improve logging supression in the tests

---

packages/lime-system/files/etc/config/lime-defaults-factory

add missing mcast defaults to 80211s

---

packages/lime-system/files/etc/config/lime-defaults-factory

Replaces .lan local domain with .thisnode.info fixes #540

---

packages/lime-system/files/usr/lib/lua/lime/wireless.lua
packages/lime-system/tests/test_lime_wireless.lua
packages/ubus-lime-location/files/usr/libexec/rpcd/lime-location

Lime location improvements

---

packages/lime-app/Makefile

closes https://github.com/libremesh/lime-packages/issues/689

recover limeapp index page

---

.luacov
packages/lime-system/files/usr/lib/lua/lime/utils.lua
packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
packages/ubus-lime-utils/tests/test_lime_utils.lua
tests/fakes/ubus.lua
tests/utils.lua

Add some tests and minnor improvements to ubus-lime-utils. Also use the new utils.printJson and utils.unsafe_shell.
TODO

Add helper functions to write rpcd tests and some ubus-lime-utils tests

---

packages/pirania/files/usr/libexec/rpcd/pirania

Wasn't importing the config for Pirania logic. That should be fixed now.

fixed missing config from pirania logic

---

packages/lime-proto-bmx6/src/bmx6hosts
packages/pirania-app/files/www/cgi-bin/pirania/client_ip
packages/pirania/files/usr/bin/voucher
packages/pirania/files/www/pirania-redirect/redirect
packages/ubus-lime-batman-adv/files/usr/libexec/rpcd/lime-batman-adv
packages/ubus-lime-bmx6/files/usr/libexec/rpcd/lime-bmx6
packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw
packages/ubus-lime-groundrouting/files/usr/libexec/rpcd/lime-groundrouting
packages/ubus-lime-location/files/usr/libexec/rpcd/lime-location
packages/ubus-lime-metrics/files/usr/libexec/rpcd/lime-metrics
packages/ubus-lime-openairview/files/usr/libexec/rpcd/lime-openairview

Replace json with jsonc

---

packages/lime-system/files/usr/lib/lua/lime/network.lua
packages/lime-system/tests/test_lime_network.lua
packages/ubus-lime-location/files/usr/libexec/rpcd/lime-location
packages/ubus-lime-location/tests/test_lime_location.lua
tests/fakes/iwinfo.lua
tests/test_iwinfo.lua

* Force shared state to update the nodes and links local database to be able to use this information right away in the lime-app so the links in the map can be updated when the position of the node is 
changed.
* Add a convenient method to get the mac addresses with globing support
* Add tests
* Cleanups

ubus-lime-location improvements

---

packages/first-boot-wizard/Makefile
packages/lua-argparse/Makefile

Correct metadata for this packages as they are source only.

Fix package architecture all

---

packages/check-internet/Makefile
packages/check-internet/Readme.md
packages/check-internet/files/usr/bin/check-internet
packages/ubus-lime-metrics/Makefile
packages/ubus-lime-metrics/files/usr/sbin/last_internet

Very simple package with a `check-internet` command that uses HTTP to check for internet.
Also use this in `last_internet`.

Add check-internet package

---

packages/lime-proto-batadv/files/usr/lib/lua/lime/proto/batadv.lua

previous commits made a white-space-mess. fix that.

lime-proto-batadv: fix indentation

---

packages/safe-upgrade/Readme.md

add r that was missing

---

packages/lime-proto-anygw/files/usr/lib/lua/lime/proto/anygw.lua

Due to dnsmasq configurations automatically generated by openwrt init
script the node name was resolved to the anygw IPv4 by the same node,
avoid this confusing behaviour and provide an host record to associate
the node name to the primary node address also on the same node.
Before this patch dns resolves:
IPv4 mynode.thisnode.info -> anygw address (10.x.0.1)
IPv6 mynode.thisnode.info -> no address
After this patch dns resolves:
IPv4 mynode.thisnode.info -> mynode specific IPv4 address (10.x.x.x)
IPv6 mynode.thisnode.info -> mynode specific IPv6 address
To make it clearer, this problem only happens with the node you are directly connected. DNS entries for nodes that are further away worked fine.

Own node name is resolved to primary IP

---

packages/lime-system/files/usr/lib/lua/lime/config.lua
packages/lime-system/files/usr/lib/lua/lime/generic_config.lua
packages/lime-system/files/usr/lib/lua/lime/utils.lua
packages/lime-system/tests/test_lime_config.lua
packages/lime-system/tests/test_lime_generic_config.lua

This fixes #719
Specifies generic configurations of type uci set to modify the configs of another package.
Example:
```bash
config generic_uci_config libremap
list uci_set "libremap.settings=libremap"
list uci_set "libremap.settings.community=our.libre.org"
list uci_set "libremap.settings.community_lat=-200.123"
list uci_set "libremap.settings.community_lon=500.9"
```
Copy a file from the assets directory into a specified path `dst`.
```bash
config copy_asset collectd
option asset 'collectd.conf'
option dst '/etc/collectd.conf'
```
Executes a file from the assets directory. The execution may be at first boot (ATFIRSTBOOT) or when lime-config is run (ATCONFIG ~~RECONFIG~~, I don't like the much the RECONFIG name). This configuration provides the functionality of uci-defaults and limeconfig …

Add generic configuration support

---

packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh

This will speed up the process, even if it will be cached if there are too many neighbour it takes a lot of time, at least 4s per neighbour. Now it will take x5 less time

shared-state: get_candidates_neigh reduce ping interval to 0.2s

---

packages/lime-system/files/etc/config/lime-defaults
packages/lime-system/files/usr/lib/lua/lime/wireless.lua
packages/lime-system/tests/test_lime_wireless.lua

Fixes #746 
Also added `htmode_2ghz` missing default.

Fix specific wireless radio config not having always priority

---

packages/lime-proto-anygw/Makefile

This change was originally proposed by @spiccinini and discussed on #709. 
Fixes #709

lime-proto-anygw remove negative dependency

---

.github/workflows/build.yml

CI: build all packages via GitHub action

---

packages/lime-system/files/etc/uci-defaults/92_add-lime-repos

Sorry, I did a mistake in #776, this fixes it.

Fix error in packages binary repository URL

---

packages/ubus-lime-utils/files/etc/profile.d/system_notes.sh

Display lime-app notes at SSH login

---

packages/lime-proto-babeld/files/usr/lib/lua/lime/proto/babeld.lua

See original report on https://lists.libremesh.org/pipermail/lime-users/2020-October/001741.html
I tested coarsely, also because I have no idea on how to check if the option is actually doing anything.

Update Babeld option "wired" -> "type"

---

libremesh.mk

Using LIME_{SECTION,CATEGORY} it is now possible to change the defaults.

libremesh.mk: allow change of SECTION/CATEGORY

---

packages/first-boot-wizard/files/etc/init.d/firstbootwizard
packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw

Also other minnor improvements.

Fbw do not start scann networks at boot

---

packages/lime-report/files/lime-report.sh

See #821 
Did not test if the output result to be too large for the popular paste bin services.
Please @G10h4ck test.

lime-report include full dmesg

---

packages/pirania/Readme.md

Add cli commands and explanation to pirania.

Pirania cli explanations on README

---

packages/lime-system/files/lib/upgrade/keep.d/libremesh

Add missing location settings file to the keep list.

lime-location: keep the location settings

---

packages/ubus-lime-utils/files/usr/libexec/rpcd/wireless-service
packages/ubus-lime-utils/tests/test_ubus_wireless_service.lua

It was left behind during a refactor

wireless-service: fix ubus enpoint name

---

packages/lime-system/files/usr/bin/migrate-wifi-bands-cfg

migrate-wifi-bands-cfg check for conf files being existing

---

packages/lime-system/files/usr/lib/lua/lime/network.lua

Check for /etc/init.d/odhcpd existence before executing

---

packages/ubus-lime-utils/files/usr/lib/lua/lime-utils-admin.lua
packages/ubus-lime-utils/files/usr/lib/lua/lime-utils.lua
packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils-admin

It fixes https://github.com/libremesh/lime-packages/issues/909

Move safe reboot to admin protected function

---

packages/babeld-auto-gw-mode/Makefile

issue fixed

---

packages/lime-docs/files/www/docs/lime-example.txt
packages/lime-proto-batadv/files/usr/lib/lua/lime/proto/batadv.lua
packages/lime-proto-batadv/tests/test_batadv.lua
packages/lime-system/files/etc/config/lime-defaults

Batman-adv add the orig_interval to the lime-* config files and set a larger default value

---

packages/shared-state-dnsmasq_servers/Makefile

As requested in my comment on #812

Fix category of shared-state-dnsmasq_servers

---

README.md

Let's clean things up a little bit and let people use use the ImageBuilder.

various readme improvements

---

packages/safe-upgrade/files/usr/sbin/safe-upgrade

This allows to test the bootstrap process in an already bootstraped LR.

Add force option to safe-upgrade bootstrap cmd

---

CHANGELOG.md

Draft: update changelog

---

.gitignore
packages/pirania/Readme.md
packages/pirania/files/etc/config/pirania
packages/pirania/files/usr/bin/captive-portal
packages/pirania/files/usr/lib/lua/voucher/utils.lua

Hi! I was working during GSoC 2024 in the project [Project Libremesh Pirania, new release. ](https://summerofcode.withgoogle.com/programs/2024/projects/J7QlUBlx)
As discussed here https://github.com/libremesh/lime-packages/issues/1077
Status:
- its working as expected except that after successfull login (with option with_vouchers=0 or 1) the web page displays a bad gateway message.

Pirania New Release - Issue/1077

---

CHANGELOG.md

periodically update the changelog

changelog: update

---

packages/watchping/files/etc/init.d/watchping

Fix #1157 
Still to be tested.

Watchping: increase wait time for interface to get up

---

TESTING.md
tools/dockertestshell

And document how to run tests without being root, fix #1195

tests: allows tests to be run outside the user's HOME

---

.github/workflows/build.yml
.github/workflows/multi-arch-build.yml

feat: add automatic build of packages for branches starting with dev* to encourage and simplify testing.

ci: build packages for dev branches
