packages/lime-system/files/etc/config/lime-defaults
I propose to use "libre-mesh.org" as default ESSID for the AP interface. 
The contained concept is not different from the previous "LiMe" ESSID but the information contained is much more accessible.
=> Changed default AP ESSID

packages/lime-system/files/etc/config/lime, packages/lime-system/files/etc/config/lime-defaults
Inserted olsr and olsr6 in the default routing protocols list.
This pull request is closely related to #9.
VLAN 14 and 15 were chosen to not conflict with BATMAN-adv ones, see discussion on #10.
=> Add olsr and olsr6 to default protocol list

packages/lime-proto-olsr/src/olsr.lua
The script was checking when the vlan is is equal to 0, but since it came from the configuration file it should be '0'.
For legacy purpose we need to use olsrd without vlan.
Without creating a new vlan inteface, olsrd will listen on  eth0 and eth1 and wlan0_adhoc.
Generating the olsrd config i get this error:
<code>
olsrd: /etc/init.d/olsrd: olsrd_write_interface() Warning: Interface 'eth1' not found, skipped
olsrd: /etc/init.d/olsrd: olsrd_write_interface() Warning: Interface 'eth0' not found, skipped
olsrd: /etc/init.d/olsrd: olsrd_write_interface() Warning: Interface 'wlan0_adhoc' not found, skipped
</code>
The /etc/config/network doesn't contains these interface's configurations.
I Think thath this happens because the function "createVlanIface" isn't called, we need a similar function …
=> Olsrd with no VLAN

packages/lime-proto-olsr6/src/olsr6.lua
This is the completion of the fix for #16 by @gabri94
=> We check if vlan is=0 to disable it. For lime-proto-olsr6.

packages/batman-adv-auto-gw-mode/Makefile, packages/batman-adv-auto-gw-mode/files/etc/watchping/wan-ok.d/batman-gw
Up to now, deselecting the firewall package (as suggested by devs [here](http://wiki.ninux.org/Libre-Mesh#Selezionare_i_moduli_di_Libre-Mesh) and [here](http://lists.libre-mesh.org/pipermail/dev/2015-September/000642.html)) results in a non working WAN connection sharing caused by the absence of a masquerading rule.
Now batman-adv-auto-gw-mode, copying the code written by @P4u for bmx6-auto-gw-mode, can add this rule.
Also a dependency to dnsmasq-dhcpv6 was added, which was used [here](/libre-mesh/lime-packages/blob/develop/packages/batman-adv-auto-gw-mode/files/etc/hotplug.d/net/99-batman-gw#L18) in the code but not present in Makefile.
=> Adding masquerading to batman-adv-auto-gw-mode

packages/batman-adv-auto-gw-mode/Makefile
The previous description was too large for menuconfig interface so it wasn't shown at all.
=> Shortened batman-adv-auto-gw-mode title for fitting menuconfig

packages/lime-system/files/etc/config/lime, packages/lime-system/files/usr/lib/lua/lime/network.lua
Here I implemented a possible approach to #18 (Separate settings for netmask and IP range auto assignment).
Two different ranges for IP auto assignment and for subnet can be set in the same option main_ipv4_address using this format: ip.ad.dr.es/range for IP/subnet. 
For example
option main_ipv4_address '192.0.128.0/17/16'
will set the IP address in the range 192.0.128.1-192.0.255.254 while the subnet mask will be /16 so leaving the first half of the subnet out of auto assignment range and available for static IPs.
Retrocompatibility is respected, so when the option is specified with just one "/" the patch is not having any effect.
This is just one of the possible way for solving #18, separating the two concepts in two options would also be a good idea.
=> Separate IP autocompletion range from subnet

packages/libluciip-lua/Makefile, packages/libluciip-lua/files/usr/lib/lua/libluciip.lua, packages/lime-system/Makefile, packages/lime-system/files/usr/lib/lua/lime/network.lua
I moved the luci.ip library from LiMe libraries to a standalone package.
I tested this with both OpenWRT Barrier Breaker and OpenWRT Chaos Calmer and it does its work solving #7.
Indeed with Chaos Calmer also the rest of the LiMe system seems working so we should really consider to merge this also in develop branch.
=> Created package with legacy luci.ip

packages/dnsmasq-lease-share/files/etc/uci-defaults/90_dnsmasq-lease-share
For the dnsmasq-lease-share module to work a running alfred is needed.
This enables its start on boot.
=> Make alfred daemon start by default when using the dnsmasq-lease-share module

packages/lime-system/files/etc/config/lime, packages/lime-system/files/etc/config/lime-defaults, packages/lime-system/files/etc/config/lime.example
Often happens to me that I write a configuration line in /etc/config/lime file but I forget to uncomment also the relative section name.
A newbie could even not know that uncommenting the section name is necessary.
I think that uncommenting the section names could be a convenient solution.
And it doesn't cause new errors.
=> Moving documentation from lime to lime.example file

packages/lime-debug/Makefile
In my opinion tcpdump mini should be included in lime-debug.
=> lime-debug: add tcpdump-mini

packages/lime-debug/Makefile, packages/lime-map-agent/Makefile, packages/lime-webui/Makefile
Using [conditional dependencies](https://wiki.openwrt.org/doc/devel/dependencies#dependency_types) for avoiding the selection of some routing packages when not explicitly requested.
This should solve #28 and partially #39.
=> Change to conditional dependencies for lime-proto-x

packages/lime-proto-olsr2/Makefile, packages/lime-proto-olsr2/src/olsr2.lua, packages/lime-system/files/etc/config/lime-defaults, packages/lime-system/files/etc/config/lime.example
I made a plugin to support the olsr2 routing daemon.
It will listen on the specified interfaces + loopback.
The main ip (olsr originator) is added as an alias to the loopback interface.
The local ipv4/v6 network is exported to the network.
=> lime_proto_olsr2

packages/batman-adv-auto-gw-mode/Makefile, packages/bmx6-auto-gw-mode/Makefile, packages/dnsmasq-distributed-hosts/Makefile, packages/dnsmasq-lease-share/Makefile
Sorry for putting the two commits in the same pull requests but both commits were changing the same line.
The first is for making the optional proto related modules to select also the relative proto module when lime-system is selected. This solves also #24.
The second is for coherence with 52bfb5a.
=> Added conditional dependencies to non-lime packages and update dependency from BMX6 to BMX7

packages/luci-app-batman-adv/Makefile
batctl seems to be hardly needed for luci-app-batman-adv :)
=> add batctl as dependency for luci-app-batman-adv

packages/lime-webui/Makefile
Seems logic for lime-webui to depend from lime-system, in my opinion.
=> Added dependency from lime-system in lime-webui

packages/lime-debug/Makefile
This package allows to see real time traffic through each interface.
It adds _approx_ 12 KB to the image when lime-debug is included.
=> Add BWM-ng package to lime-debug

packages/lime-basic-uing/Makefile
compiled for lede17010 ath9k
manuelle installation:
opkg install http://gadow.freifunk.net:8004/srv2/lede/lede-sdk-1701/bin/packages/mips_24kc/packages/luci-lib-jquery-1-4_1.4-1_mips_24kc.ipk
opkg install http://gadow.freifunk.net:8004/srv2/lede/lede-sdk-1701/bin/packages/mips_24kc/packages/luci-lib-jquery-flot-0-8_0.8.1-1_mips_24kc.ipk
opkg install http://gadow.freifunk.net:8004/srv2/lede/lede-sdk-1701/bin/packages/mips_24kc/packages/luci-mod-status_-_mips_24kc.ipk
=> luci-mod-status: use public interface of luci.model.network.wifinet

packages/lime-system/files/etc/config/lime-example
I didn't test this but the encryption type configuration should be needed in the example of a private ap configuration.
=> Add line for psk in example of private ap mode configuration

packages/safe-reboot/files/usr/sbin/safe-reboot
Adds discard functionality to safe-reboot, which allows to manually discard the last changes done to /etc after a safe-reboot call.
Corrects overlay paths in safe-reboot script.
=> Safe reboot discard action

packages/luci-app-batman-adv/files/usr/lib/lua/luci/controller/batman.lua
It solves part of the issue #110.
I have no environment to test the Gateways section, just the Originators one.
=> Fix batman-adv Originators Status WebUI.

packages/lime-webui/luasrc/controller/lime.lua
Replaced the logout function of the Simple Administration area with the same code as the one in the Advanced Administration area.
=> Fix #141 - Logout error on Simple Config area

packages/lime-system/files/usr/bin/lime-apply
If hostname does not changes, bmx6 can be just reloaded.
If nostname changes, bmx6 must be restarted to update hostname
information. Also watchping must be restarted for checking if Internet
must be announced or not (and execute actions over bmx6).
=> lime-apply check if hostname changes and restart watchping

packages/fft-eval/Makefile
This new version doesn't require SDL and is prepared to work with outputs from ath9k and ath10k and channel width of 20 and 40 Mhz.
=> Updates fft-eval to last mainstream version

packages/lime-system/files/etc/firewall.lime, packages/lime-system/files/usr/lib/lua/lime/firewall.lua
To get the stock firewall working nicely, add a all lm_* interfaces
to the 'lan' zone. And we really shouldn't change the defaults for
the wan zone (!), why ever this was done, it really shouldn't.
If the wan interface isn't used as a wan interface, it shouldn't be
called wan -- calling it wan and opening the firewall for all
incoming packages while keeping SSH with no-password-auth open is
real madness and will get people pwned.
=> firewall: add lm_* interfaces to 'lan' zone

packages/lime-docs/Makefile
Merging of pull request #140 introduced the following error when compiling using LEDE buildroot (using lime-sdk such errors are ignored maybe?):
```
* check_data_file_clashes: Package lime-docs wants to install file /home/ilario/software/lede3/build_dir/target-powerpc_8540_musl/root-mpc85xx/www/docs/config.txt
But that file is already provided by package  * lime-docs-minimal
* opkg_install_cmd: Cannot install package lime-docs.
```
So this fixes removing `config.txt` from lime-docs and introducing it via lime-docs-minimal as a dependency of lime-docs.
=> Removing overlap between lime-docs and lime-docs-minimal

packages/lime-proto-bmx6/Makefile, packages/lime-proto-bmx7/Makefile, packages/lime-proto-wan/Makefile
lime-proto-wan and lime-proto-bmx[6/7] only depend on iptables if
lede/openwrt firewall is not selected.
=> Do not depend on iptables if fw3 installed

packages/lime-docs/Makefile
This change requires the documentation in lime-web to start with a prefix indicating the language e.g `en_config.txt`, see discussion on libremesh/lime-web#28
=> Add lime-docs-it

packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
On first boot create opkg feeds repostory file and libremesh official
signing key. So now opkg can be used for installing libremesh packages.
Example: opkg update && opkg install lime-full
=> Add libremesh opkg repositories

packages/lime-basic-uing/Makefile, packages/lime-basic/Makefile
As explained in #184, its merge introduced a dependency problem which seemed innocuous (?) but appears to break continuous integration (#186).
=> Avoid lime-basic to select lime-docs-minimal when lime-docs is selected by lime-full

packages/lime-basic-uing/Makefile, packages/lime-basic/Makefile, packages/lime-docs/Makefile
Following the discussion on #183, lime-docs-minimal was installing `en_config.txt` from lime-web. This file is installed also by lime-docs, for avoiding the errors caused by this overlap, a complex dependency was required, but appears to be broken (it compiles on my laptop but @nicopace is having problems with this).
Needless to say, the easiest solution is the one proposed in #183 (removing the overlap).
=> lime-docs-minimal just installs lime-example

README.md
LEDE buildroot does not compile following instructions in readme because of dependencies on libremap from lime-full. The addition of libremap feeds is inserted in readme.
In [lime-sdk feeds](/libremesh/lime-sdk/blob/master/feeds.conf.default) also lime-ui-ng is present, so I add also this which will be likely needed soon.
=> Update feeds in readme/buildroot to the ones present in lime-sdk

.travis.yml
This could be useful for verifying dependency problems which can be different for lime_default and other LibreMesh flavors.
=> Add lime_zero and lime_mini to continuous integration

packages/lime-webui/luasrc/controller/lime.lua
the attended sysupgrade shoudl simplify sysupgrades. If the app is
installed an entry should appear in the simple admin config.
@p4u
Signed-off-by: Paul Spooren <paul@spooren.de>
=> luci-webview: add attendedsysupgrade tab if exists

packages/lime-proto-batadv/src/batadv.lua, packages/lime-system/files/usr/bin/lime-apply, packages/lime-system/files/usr/lib/lua/lime/proto/lan.lua
If batman-adv is not enabled, ALFRED does not start cause it waits for bat0 interface (which does not exist). However if ALFRED is not running, dnsmasq distributed leases does not work. On a network with LAN enabled more than one libremesh nodes might be wired connected and lease share must work between them.
This commit solves this case.
1. If batadv enabled on configuration, set ALFRED batman interface to bat0.
2. If batadv not enabled but LAN is, set it to "none", so ALFRED still works on LAN.
=> lime-config: configure ALFRED batman interface

packages/luci-app-batman-adv/files/usr/lib/lua/luci/controller/batman.lua, packages/luci-app-batman-adv/files/usr/lib/lua/luci/view/batman.htm
This also implies dropping all the 'batctl vm' related code,
since now master or slave mode is an alfred status, that exceeds
the scope of the visualization tool, so shouldn't be touched by this luci-app
=> batctl vd is gone. use batadv-vis.

packages/smonit/Makefile
Required for some profiles which do not have CRON enabled by default
Fix #221
=> Add CRON as dependency for smonit

packages/lime-system/Makefile, packages/lime-system/files/usr/lib/lua/lime/wireless.lua
This is expected to correctly detect available radio modes (abgnc) on
meshpotato too, before being merged need testing on meshpotato too
I reopen the PR because github someway got stuck believing the other PR has been merged while it is not
=> Use libiwinfo-lua do detect radio mode instead of uci

.ci/after_success.sh, .travis.yml
Pull requests sent from forked repositories do not have access to encrypted variables or data.
As you can not access the variables you can not decrypt the key and perform the tasks in after_success.sh
This change verifies that the action comes from the libremesh/lime-packages repository and not from a fork.
=> Fix travis fails on forks pull request

README.md
`firewall` package is not deprecated anymore from default LibreMesh setup. Refer to libremesh/lime-sdk@f4f5e6f
=> Stop suggesting to deselect firewall in menuconfig

packages/lime-proto-wan/src/wan.lua
this allows to ping6 and ssh into routers through WAN port using fe80::/10 addresses
=> lime-proto-wan: ensure link-local traffic over WAN is always allowed

packages/lime-proto-bmx6/src/85-add-bmx6-addresses-to-hosts
Adds a new entry to /etc/config/dhcp to tell dnsmasq look into
/var/hosts/bmx6 (for .mesh domains provided by lime-proto-bmx6 package).
It ensures that .mesh domains are resolved without depending in any other package.
=> Add bmx6 hosts file to dnsmasq

packages/lime-docs/files/lime-example
Interface specific options does not work when included in /etc/config/lime-defaults, refer to @p4u's answer in lime-dev mailing list: https://lists.libremesh.org/pipermail/lime-dev/2017-August/000976.html
=> Document that specific options can't go in /etc/config/lime-defaults

packages/luci-app-lime-location/files/usr/lib/lua/luci/view/location/location.htm
As per title, this commit adds a link in the `/cgi-bin/luci/lime/location` page pointing to http://libremap.net it opens the link in new tab
=> Adds link to LibreMap.net in location page. Fixes #120

packages/dnsmasq-distributed-hosts/Makefile, packages/dnsmasq-lease-share/Makefile
Thanks to bcfae39, alfred works also when batman-adv is missing.
Adapt *dnsmasq-distributed-hosts* and *dnsmasq-lease-share* packages descriptions to this change.
=> Pkg description reflecting that Alfred doesn't need batman-adv

packages/safe-reboot/files/usr/sbin/safe-reboot
The check is done right before deleting $dir_etc, if no file is found
then a message is printed and the script exits with status code 2
I tried to be consistent with the behaviour of this script regarding error code and message.
How can I improve this PR?
=> Checks for $file_etc_lastgood existance before removal. Fixes #203

packages/lime-webui/po/qqq/lime-webui.po
The qqq language code is for string documentation for translators. I haven't filled in the documentation messages yet.
I'm not sure if I've done the correct steps to create this pull request...?
=> create qqq language code

packages/lime-proto-bmx6/src/bmx6hosts_dnsmasq_update
This avoids the chance that some other process will HUP dnsmasq
while /var/hosts/bmx6 is half-baked.
=> bmx6hosts_dnsmasq_update rewrite: update /var/hosts/bmx6 in an atomic way

packages/lime-basic/Makefile, packages/lime-proto-anygw/Makefile, packages/lime-proto-bmx6/Makefile
Kmod-ebtables needs to be explicity selected due a strict dependency on
ebtables package.
Add conditional dependency in package lime-proto-bmx6 on ebtables and
lime-proto-batadv. Iff batadv is not installed bmx6 does not need
ebtables.
=> Changes on kmod-ebtables package dependency

packages/lime-full/Makefile
Install full luci instead of *only* the luci-mod-admin-full. The package luci-proto-ppp is additionally installed which result's in a squashed file size increase of < 1KB.
=> replace luci{-mod-admin-full,} to fix #260

packages/lime-proto-bmx7/src/bmx7.lua
The [SMS plugin](https://github.com/bmx-routing/bmx7#sms-plugin) can be very useful for various projects
See https://github.com/libremesh/lime-packages/issues/104
=> lime-proto-bmx7: enable SMS plugin

packages/lime-system/files/usr/lib/lua/lime/config.lua
Method config.get() function can now be called with a third (optional) value
if it's not Null and the option is not found, will be the returned value.
This allows the easy integration of new options which might be not (yet)
introduced in lime-defaults of a node after upgrading.
A Warning message is printed if default value used.
details on #278
=> Introduce an optional default value in config.get()

packages/watchping/files/etc/init.d/watchping, packages/watchping/files/etc/uci-defaults/90_watchping, packages/watchping/files/etc/watchping/wan6-fail.d/README, packages/watchping/files/etc/watchping/wan6-ok.d/README, packages/watchping/files/usr/bin/watchping
all work done by @dangowrt and based on https://github.com/libremesh/lime-packages/pull/71
This PR does not include the bmx6 script as the discussion is still
ongoing. As IPv6 watchping functionality is not directly related this
can be merged independently.
=> enable watchping to check for ipv6 connectivity

packages/lime-system/files/usr/bin/lime-config
using this parameter deletes /etc/config/lime and is usefull when new
lime-defaults are set by network-profile or something else.
tested on x86/64
=> lime-config: add --reset/-r parameter

packages/lime-system/files/usr/lib/lua/lime/config.lua
config.get_bool: 
If used with real boolean values like 1 or true instead of strings like "1" and "true" the function fails. 
config.get:
when the default value is a array/table the print message fails
=> config.lua: get_bool & defcnf hotfix

packages/lime-system/files/usr/lib/lua/lime/wireless.lua
If specific radio information are set without a suffix the current configuration fails.
To fix this if *channel_<suffix>* ins't found it will fall back to *channel*
=> wireless.lua: fallback channel option

packages/lime-system/files/usr/lib/lua/lime/network.lua
As described in #287, network.lua was correctly identifying invalid IPv4 (in the specific case IPs which were overlapping with anygw IP, so the first of the domain) but was not setting correctly the netmask in this case.
Let me know if there is a more elegant way to do this, I expected it was possible to change just the IPv4 address with just one command without changing the prefix (something like `ipv4_template:host(mc:maxhost())`) but I couldn't find it.
=> network.lua: set again the prefix in case of invalid IPv4 address, fix #287

packages/lime-system/files/etc/config/lime-defaults, packages/lime-system/files/usr/lib/lua/lime/network.lua
introduce new lime-defaults option use_odhcpd (default currently on
false) which dis- or enables odhcpd as primary dhcp server.
replace io.popen by os.execute for a simpler syntax
=> network.lua: add use_odhcpd option

packages/lime-smart-wifi/Makefile, packages/lime-smart-wifi/files/etc/uci-defaults/90_lime-smart-wifi, packages/lime-smart-wifi/src/lime-smart-wifi.lua, packages/lime-system/files/usr/lib/lua/lime/utils.lua
fix separate Mesh and AP radio based on frequencies #306
1 radio with dual band is not supported due to missing device for
testing, this will be added.
automatically swaps channels if multible radios on same freq exist
tested on tp link wdr 4300
also introduce new function to utils to check if an element is inside an
array
reopend due to git messup
=> lime-smart-wifi: add package, fix #306

packages/lime-system/files/usr/lib/lua/lime/wireless.lua
due to the if block the local variable distance is not readable by the
following code resulting in an undeclared (nil) variable error.
please merge asap as `lime-config` is broken
=> wireless: fixup local distance

packages/lime-smart-wifi/files/etc/uci-defaults/90_lime-smart-wifi
currently the wifi channels become an option instead of a list
=> lime-smart-wifi: fix uci-defaults list

packages/lime-proto-bmx6/src/bmx6.lua, packages/lime-proto-bmx7/src/bmx7.lua
max rate is configured in Bits not KBits. 54000 would result in
a estimated max connection of 54KBit while it's really 54Mbit.
=> lime-proto-bmx6,7: fix maxRate for wifi

packages/lime-docs/files/lime-example, packages/lime-system/files/usr/lib/lua/lime/utils.lua, packages/lime-system/files/usr/lib/lua/lime/wireless.lua
Currently setting specific radio options lead to a total overwrite of
all settings provided in lime and lime-defaults.
Changing just the channel results in a bad config as ssid, etc. are empty.
Instead, this patch introduces the tableConcat function where the
specific settings are attached to the defaults and so overwrite them.
=> lime-system: add function arrayConcat to fix wifi

packages/lime-proto-bmx6/src/bmx6.lua, packages/lime-proto-bmx7/src/bmx7.lua
if the plugin is activated but the plugin not installed bmx7 crashes on
startup.
=> lime-proto-bmx{6,7}: sms only active if installed

packages/lime-proto-bmx7/src/bmx7.lua
=> lime-proto-bmx7: enable iwinfo plugin if installed

packages/lime-proto-bmx6/src/bmx6.lua, packages/lime-proto-bmx7/src/bmx7.lua
blind copy&paste is bad and I feel bad
also setting manually bmx{6,7}_wifi_rate_max to false disables
automatically the rateMax parameter. This is useful as bmx7 now does
good bandwidth estimations itself [1]
[1] https://github.com/bmx-routing/bmx7/pull/15
=> WIP: lime-proto-bmx{6,7}: fixup maxrate and add "false"

packages/lime-hwd-openwrt-wan/src/openwrt_wan.lua, packages/lime-hwd-openwrt-wan/src/openwrt_wan.sh
currently a missing wan interfaces screws the config, the following
string will be inserted:
WARNING: Variable 'wan' does not exist or is not an array/object
this happens for instance on a raspberry pi with only one eth port.
If no wan is detected, just leave it unconfigured.
=> lime-hwd-openwrt-wan: fix script if missing wan

packages/lime-system/files/usr/lib/lua/lime/utils.lua
macid is like netid a md5sum hash of mac. The idea is to have static IP
addresses for devices which sustain after a reset or reflash, while
keeping collision chance as lower as using %M aka the real mac.
This is due to the fact that when using similar devices, they tend to
have nearly equal mac addresses.
A possible network could look like this: 10.%m1.%m2.%m3/25 which would
result in a collision chance of `n/(2 * 256^2)` where `n` is the number of
used devices.
=> [RFC]utils: introduce %m in IPs to use macid

packages/lime-system/files/usr/lib/lua/lime/utils.lua
the mac is stored as a table and thereby causes an error when trying
concat it with another string.
also fix indent
=> lime-system: fixup mac table handling

packages/lime-webui/po/es/lime-webui.po
In order to work with TranslateWiki, @Nikerabbit asked to change the .po files from ISO-8859 to UTF-8. Two files (po/limeweb-ui.pot and po/qqq/limeweb-ui.po) were already in UTF-8. In this commit, I changed the remaining file po/es/limeweb-ui.po to UTF-8.
@nicoechaniz thinks it will be ok with the routers, but says to ask @G10h4ck .
@G10h4ck would be surprised if UTF-8 works on the routers.
Opinions? Solutions? Ways to test without bricking routers?
=> change .po file encoding to UTF-8

packages/lime-system/files/usr/lib/lua/lime/utils.lua, packages/lime-system/files/usr/lib/lua/lime/wireless.lua
I don't know what lead to the arrayContact function but it can't be used
in that case: `options` are loaded via `config.get_all()` and result in
an dict like table. Specific options are also a dict and can't be added
as an array.
Also both function return the value rather then manipulating the
incomming table. Therebey wireless.lua is adjusted.
Also cleans some whitspace errors
=> utils: add function tableAppend

packages/lime-proto-bmx7/src/bmx7.lua, packages/lime-system/files/etc/config/lime-defaults
bmx7 estimates the maxRate of wifi interfaces by iteself, thereby don't
set a static value of 54M in times of AC mesh connections
=> lime-proto-bmx7: use auto rate

packages/lime-system/files/usr/lib/lua/lime/wireless.lua
These modifications allow to indicate to which radios we want to apply the modes.
For example if I want to open an ap but only in the 2ghz radio the configuration in lime-config is:
```
config lime 'wifi'
list modes 'ap_2ghz'
list modes 'adhoc'
...
```
In the same way it could indicate that I only want to raise the mesh in 5ghz
```
config lime 'wifi'
list modes 'ap_2ghz'
list modes 'adhoc_5ghz'
...
```
If no particular frequency is indicated, the mode apply to all radios.
=> Indicate to which kind of radios we want to apply wireless modes

packages/sprunge/src/sprunge.sh
evaluating the command directly as ${2} didn't work well with commands
that included redirects, use eval "${2}" for correct behaviour
Improve readability by breaking lines longer then 80 chars
=> Fix sprunge evaluating commands with redirects

packages/lime-docs/files/lime-example
Specify that for using ieee802.11s mesh encryption the wpad-mini package is not enough.
Related discussions on: libremesh/chef#8 and #208
=> lime-example document encrypted mesh dependency on wpad-mesh

packages/lime-docs/files/lime-example
The documentation of wireless client mode was a bit incorrect: the wireless interface is not wlan0-client but wlan0-sta, this should fix #383 
This also adds a comment recommending to check if the used radio name exists
=> lime-example improved documentation for wireless client mode

packages/lime-system/files/usr/lib/lua/lime/network.lua
In case an invalid IPv4 was set in /etc/config/lime, network.lua silently sets a fallback one.
The users can have troubles in understanding what happened ([example](https://lists.libremesh.org/pipermail/lime-users/2018-November/001333.html)), this could be mitigated by a warning message.
=> Added warning for invalid IPv4 settings

packages/lime-docs/files/lime-example, packages/lime-system/files/usr/lib/lua/lime/network.lua, packages/lime-system/files/usr/lib/lua/lime/proto/static.lua
Depends on #420 
This should fix #409 and #408 
Changes the settings of a static IP from
```
list protocols 'static:1.2.3.4/24'
list protocols 'static:1:2:3:4:5:6:7:8/64'
```
to
```
list protocols 'static'
option static_ipv4 '192.168.1.2/24'
option static_gateway_ipv4 '192.168.1.1'
option static_ipv6 '2a00:1508:0a00::1234/64'
option static_gateway_ipv6 'fe80::1'
```
the advantages are: possibility to set a gateway, support for any IPv6 format (compressed with :: or not).
=> Static proto: add setting for gateway and clean IPv6 setting

packages/lime-docs/files/lime-example
Updated:
- "parametrization" to "parameterization"
- "encryted" to "encrypted"
=> Update spelling in lime-example

.travis.yml, libremesh.sdk.config, packages/bmx7-auto-gw-bw-mode/Makefile, packages/bmx7-auto-gw-bw-mode/files/etc/init.d/bmx7-auto-bw, packages/bmx7-auto-gw-bw-mode/files/etc/watchping/wan-ok.d/bmx7-gw-bwtest, packages/bmx7-auto-gw-bw-mode/files/usr/sbin/bmx7-auto-bw-test
If the node is an Internet gateway, checks the bandwidth (downloads a
10MB file) and announces it to the mesh. It integrates with watchping
and bmx7-auto-gw-mode.
The check is automatically done via crontab every 6 hours.
=> Introduce bmx7-auto-gw-bw-mode package

packages/lua-argparse/Makefile
This package allow easy development of powerful lua command line interfaces.
This is a dependency of the `safeuprade` package (to be pushed later).
=> add lua-argparse package

packages/bmx7-mdns/Makefile, packages/lime-basic/Makefile, packages/luci-app-lime-location/Makefile
else we get this error
Package bmx7-mdns version 0.1-1 has no valid architecture, ignoring.
Package lime-basic-no-ui version 2019-01-31-1548943035 has no valid architecture, ignoring.
Package lime-basic version 2019-01-31-1548943035 has no valid architecture, ignoring.
Package lime-webui version 2019-01-31-1548943035 has no valid architecture, ignoring.
=> PKGARCH:=all at lime-basic and luci, bmx7-mdns

packages/sprunge/Makefile, packages/sprunge/src/ix.sh, packages/sprunge/src/sprunge.sh
Waiting for the discussion in #458 to converge, this adds the ix.io client inside the sprunge package, as both sprunge.us and ix.io are very similar and the usage of one or of another usually depends on their websites up or down state.
Please note that the HTTP headers in the ix.sh script are terminated with a \r\n instead of just a \n (this was needed at the moment of writing, otherwise a 400 Bad Request error was received).
=> Add ix.io client to sprunge package

packages/fft-eval/Makefile
Some time ago there were a couple of changes from fft-eval that were sent to upstream, after that the Makefile was broken and as it block the build of libremesh was removed. This pull request includes a Makefile that works.
=> Add fft-eval again

packages/lime-app/Makefile, packages/ubus-lime-batman-adv/Makefile, packages/ubus-lime-openairview/Makefile, packages/ubus-lime-openairview/Readme.md, packages/ubus-lime-openairview/files/usr/libexec/rpcd/lime-openairview
Expose via ubus the result of the spectrum analysis obtained by fft-eval
`ubus call lime-openairview spectral_scan '{"device":"wlan1-adhoc", "spectrum":"5ghz"`
```
{  
"spectrum":{  
"epoch":1550326676,
"samples":[  
{  
"noise":-93,
"central_freq":5520,
"rssi":9,
"data":[  
[  
"5510",
"-108.596024"
],
[  
"5510.356934",
"-106.097244"
],
[  
"5510.714355",
"-108.596024"
],
[  
"5511.071289",
"-102.575424"
],
[  
"5511.428711",
"-100.076645"
],
[  
"5511.785645",
"-96.554825"
],
[  
"5512.143066",
"-106.097244"
],
[  
"5512.5",
"-106.097244"
],
[  
"5512.856934",
"-96.554825"
],
[  
"5513.214355",
"-93.529465"
],
[  
"5513.571289",
"-112.117844"
],
[  
"5513.928711",
"-97.310593"
],
[  
"5514.285645",
"-106.097244"
],
[  
"5514.643066",
"-106.097244"
],
[  
"5515",
"-118.138443"
],
[ …
```
=> Ubus - Spectral scan in lime-openairview

packages/safe-upgrade/Makefile, packages/safe-upgrade/bootscript_gen.py, packages/safe-upgrade/files/usr/sbin/safe-upgrade
Provides dual-boot functionality with automatic revert safety, mainly for >=16MB devices like the LibreRouter
=> Add safe-upgrade package

packages/safe-upgrade/files/usr/sbin/safe-upgrade
When using `safe-upgrade upgrade -n image.bin` the automatic restart script wasn't installed to the new partition.
=> safe-upgrade: fix restart script not preserved when upgrading with -n

packages/first-boot-wizard/Makefile, packages/first-boot-wizard/files/bin/firstbootwizard, packages/first-boot-wizard/files/etc/init.d/firstbootwizard, packages/first-boot-wizard/files/etc/uci-defaults/zzzz-serve-lime-config, packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua, packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard/functools.lua, packages/ubus-lime-fbw/Makefile, packages/ubus-lime-fbw/README.md, packages/ubus-lime-fbw/files/etc/init.d/ubus-lime-fbw, packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw, packages/ubus-lime-fbw/files/usr/share/rpcd/acl.d/lime-fbw.json
First Boot Wizar allows you to analyze nearby mesh nodes and extract the base configuration to be part of the network. Once copied the configurations the user can select in LimeApp which one to use to configure his node or if he wants to create a new network.
**How does it work?**
If when turning on the node detects that it does not have a configuration applied (/etc/first_run exist) it scans all the networks and selects the mesh and ad-hocs. Then switch to the channel of each network and try to make a wget via fe80 to extract the configuration. After doing the full scan it goes back to the previous configuration.
The downloaded lime-default files are saved in /tmp and are exposed via lime-app to the user.
There are still many things to improve and optimize, but this version meets the MVP …
=> Add First Boot Wizard and ubus-lime-fbw packages

packages/lime-app/Makefile
The current version of LimeApp in lime-packages is outdated with the current state of development.
I managed to implement a **continuous integration between libremesh/lime-app and libremesh/lime-packages**. When I publish a release (via tag) it automatically creates a branch with the Makefile updated in lime-packages.
This version improves the handling of calls to UBUS to avoid congestion and the first screens of FirstBootWizard in case the ubus module is installed.
There are also several fixes and minor features like text2speach in the alignment screen.
=> LimeApp updated to v0.2.0-alpha.5

packages/lime-app/Makefile
Related to #484 
Improved version for handling errors in the Internet connection.
=> LimeApp updated to v0.2.0-alpha.6

packages/lime-app/Makefile
Improves interoperability between browsers by removing the use of the crypro API, which Chrome only enables in secure sources (HTTPS and localhost).
=> LimeApp updated to v0.2.0-alpha.7

packages/ubus-lime-utils/README.md, packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
Exposing safe-reboot methods via ubus is going to be useful to make changes from the ui safely.
It would be very interesting to have the timestamp of the next scheduled restart. Currently safe-reboot doesn't have how to get this information or I don't know where to extract it from.
| Path       | Procedure       | Signature                                                         | Description                                                                                                                                                                                                                                                                                                                           |
| ---------- | --------------- | …
=> safe-reboot via Ubus

packages/ubus-lime-metrics/Makefile, packages/ubus-lime-metrics/files/etc/uci-defaults/99-save-last-known-path-to-internet, packages/ubus-lime-metrics/files/usr/sbin/last_internet
Recovers the ability to remember in the node the last route to the Internet. At the moment it does it only for bmx6 but it should contemplate other protocols layer 3.
The script runs every 30 minutes but only writes changes if it detects a difference with the previous route.
It is important to diagnose network problems, such as nodes gone off or broken links.
LimeApp uses this route to check for problems when the internet is not detected.
This recovers the work done by @nicoechaniz  in lime-orange-rpc (https://github.com/libremesh/lime-ui-ng/blob/8a4fb7df3ec9809d1f4dbf50ad590428a4b3bf1f/lime-api-orange-rpc/files/usr/sbin/internet_path)
=> Add last_internet script

.github/stale.yml
I was recently reviewing the issues and pull-request of lime-packages. It is a very arduous and repetitive task. It occurred to me to look for some tool to do that monitoring and to warn of issues or pull-request abandoned, since many of them can be important. I found that github has its own bot to perform this task: stale.
This pull request incorporates the configuration for this bot, the proposed operation is as follows:
- Alert about issues without activity for X days (one year, two months, whatever we want)
- If after that warning there is no activity after Y number of days the issue or pull request is closed and a particular tag (autoclose, wontfix, etc) is applied.
- The bot ignores the issues marked with the tags we want (release-blocker, bug, user history, etc).
I think it's a …
=> Add stale github bot

packages/lime-app/Makefile
Remove window.crypto. Chrome only allows its use in secure environments (https or localhost)
Instead I implement a simple form of hash that fulfills the function.
=> LimeApp updated to v0.2.0-alpha.9 - Fix api calls

packages/ubus-lime-openairview/files/usr/libexec/rpcd/lime-openairview
Add mesh interfaces in get_interfaces, currently only captures adhoc networks.
Bug found at the community networks meeting in Sao Paulo.
=> Fix lime-openairview

packages/lime-app/files/lime-app.defaults
This allows you to consume the ubus api from another domain. This way LimeApp can consume the api of the different nodes without having to recharge all the assets.
=> Enable ubus cors in uhttpd

packages/lime-system/Makefile
Fixes `/usr/bin/lua: /usr/bin/lime-config:54: attempt to call a nil` value when running lime-config
Tested in a LibreRouter, after applying fix:
```
root@LiMe-8851a5:~# lime-config 
Clearing wireless config...
Clearing network config...
Disabling odhcpd
sh: /etc/init.d/odhcpd: not found
Cleaning dnsmasq
Disabling 6relayd...
lime.proto.babeld.configure(...)
Use fallback value for network.babeld_over_librenet6: false
lime.proto.babeld.setup_interface(...)	eth0.1
lime.proto.babeld.setup_interface(...)	wlan1-ap	ignored
lime.proto.babeld.setup_interface(...)	wlan0-apname	ignored
lime.proto.babeld.setup_interface(...)	wlan1-apname	ignored
lime.proto.babeld.setup_interface(...)	wlan2-mesh
lime.proto.babeld.setup_interface(...)	wlan0-mesh
lime.proto.babeld.setup_interface(...)	wlan2-ap	ignored …
```
=> create hotplug.d/lime-config directory at install time

packages/lime-app/Makefile
This version includes FirstBootWizard support and full transalations in english, spanish and brazilian portuguese.
See more changes in https://github.com/libremesh/lime-app/releases/tag/v0.2.0-alpha.10
=> LimeApp updated to v0.2.0-alpha.10

packages/shared-state-persist/Makefile, packages/shared-state-persist/files/etc/hotplug.d/block/90-shared-state, packages/shared-state-persist/files/etc/uci-defaults/50-set-automount, packages/shared-state-persist/files/usr/bin/shared-state-persist
This package allows to persist shared-state data on USB storage devices.
It works automatically, the user only has to plug a USB flash drive with FAT32 partition and shared-state-persist analyzes its content and configures the router.
This reacts to mounted devices according to the following logic:
- The mounted storage device has no shared-state folder (creates the directory and uses it after copying the actual /var/shared-state)
- The mounted device has the folder shared-state (uses it as is)
- If not devices found use the default /var/shared-state
> Info: Shared-state-persist use the first result found.
=> Add shared-state-persist package

packages/lime-system/files/etc/config/lime-defaults-factory
channel 157 is FCC approved for outdoor use
Signed-off-by: Santiago Piccinini <spiccinini@altermundi.net>
TODO: test with devices with only one radio
=> use channels 157 and 48 for 5.8GHz

packages/shared-state-persist/files/usr/bin/shared-state-persist, packages/shared-state/files/etc/config/shared-state, packages/shared-state/files/usr/bin/shared-state
Allows you to specify additional IPs addresses using uci configurations.
Until we advance in a more fully functional scheme this option will allow us to maintain one or more masters or replicators. It is not necessary that they are routers, it is possible to program a http server for some more powerful device or destined to that end.
These ips are determined by a list in /etc/config/shared-state. 
A commented option is included in this pull request as an example.
=> Add shared-state.options.candidates list

packages/safe-upgrade/files/usr/sbin/safe-upgrade, packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
Solve a couple of typing errors in safe-upgrade and an extra character in lime-utills
=> Fix typos in lime-utils and safe-upgrade

packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
It was selecting too much, filtering out ip6 that partially matched with short ips.
=> Corrects own ip filtering

packages/shared-state/files/www/cgi-bin/shared-state
Due to the fact that uhttpd may interrupt the script for various reasons
and the incapability to handle signals in lua without requiring more
dependencies, the cgi-bin script could terminate witout cleaning up the
temporary files created.
The script should just check params and call shared-state.
So to reasonably solve this problem I just rewrote it in ASH that doesn't
require temporary files at all.
=> Fix shared-state cgi-bin script /tmp/lua_* pollution

packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
Expected behaviour: when the lastrun file exists but it's empty, the program continues.
Actual behaviour: when the lastrun file exists but it's empty, the program exits.
TODO: check why the lastrun file is empty in the first place.
=> Fixes empty file bug.

packages/shared-state-dnsmasq_leases/files/usr/bin/dnsmasq-lease-share.sh
@gmarcos87 and I have seen that when the sync is triggered in each update, the router can't cope with it and stalls processes enough to drain the resources of the device.
While this gets fixed, it is safer if only cron-based updates are run.
=> Removes event-based sync as it creates a loop that drains router resources

packages/shared-state-nodes_and_links/Makefile, packages/shared-state-nodes_and_links/files/etc/shared-state/publishers/shared-state-publish_nodes_and_links, packages/shared-state-nodes_and_links/files/etc/uci-defaults/shared-state-bat_nodes_and_links, packages/shared-state-nodes_and_links/files/usr/bin/shared-state-publish_nodes_and_links, packages/ubus-lime-location/files/usr/libexec/rpcd/lime-location
This package allows to distribute via shared-state the location of the nodes, their macs and their wifi links with other macs. 
Modify ubus-lime-location to consume the information:
```
root@si-fridge:~# ubus call lime-location nodes_and_links
{
"si-fridge": {
"links: [
"a0:f3:c1:6c:32:75",
"c0:4a:00:fc:41:55"
"14:cc:20:ad:b0:1d"
"64:70:02:4e:cd:0b"
],
"coordinates: {
"lon": "-64.39936101436615",
"lat": "-31.799673850547368"
},
"macs": [
"02:75:ba:dc:0d:51"
"02:75:ba:dc:0d:52"
],
"hostname": "si-fridge"
}
}
```
It is useful to show a map of the network in a decentralized way in lime-app
=> Adds shared-state-nodes_and_links

packages/shared-state-dnsmasq_leases/files/etc/uci-defaults/90_dnsmasq-lease-share, packages/shared-state-dnsmasq_leases/files/usr/bin/shared-state-generate_dnsmasq_leases
_authors: @nicopace and @gmarcos87_
The behaviour we are trying to debug is related to dnsmasq consuming an increasing amount of resources.
We suspect that this is caused by these messages:
```bash
Thu Jun 20 16:23:32 2019 daemon.warn dnsmasq-dhcp[6684]: duplicate IP address 2801:1e8:2::6c60:9100 (ql-gioiajesinico) in dhcp-config directive
...
Thu Jun 20 16:23:32 2019 daemon.warn dnsmasq-dhcp[6684]: duplicate IP address 10.5.0.96 (ql-gioiajesinico) in dhcp-config directive
...
Thu Jun 20 16:23:32 2019 daemon.err dnsmasq[6684]: duplicate dhcp-host IP address 10.5.5.123 at line 225 of /tmp/dhcp.hosts_remote
```
These are the configs that are being used in the node that the issue is happening, it can be found in `/tmp/etc/dnsmasq.conf.cfg*`:
```
conf-file=/etc/dnsmasq.conf
dhcp-authoritative …
```
=> Fix DNSMASQ malfunctioning in LibreMesh

packages/dnsmasq-lease-share/src/dnsmasq-lease-share.sh
In my testing, I saw dnsmasq use a very large amount of CPU, and calling dnsmasq-leash-share.sh over and over again with the same collections of arguments.
I noticed that this script wasn't calling the lua file with any arguments.
Making this change resolves the dnsmasq process using lots of CPU.
Is there anything obvious that this change will break? I'm actually a little confused how DHCP was working properly in my mesh before making this change.
=> Have dnsmasq-lease-share.sh forward it's arguments to dnsmasq-lease-share.lua

packages/safe-upgrade/files/usr/sbin/safe-upgrade
The idea behing having a --preserve-full-config options was that if safe-upgrade was run without -n then it will preserve a minimal configuration and with --preeserve-full-config it will preserve the whole config as sysupgrade does. 
The thing is that the minimal config preservation is not implemented so having a --preserve-full-config is confusing. So removing this option for now.
This fixes #547
=> safe-upgrade: remove --preserve-full-config cmdline arg

packages/shared-state-bat_hosts/files/usr/bin/shared-state-generate_bat_hosts
Shared-state is using the mac address as the unique key when publishing interfaces in shared-state-bat-hosts. 
This is not bad, except that the bat0 interface gets a random mac address at every startup. This generates duplicate entries in bat-hosts (different macs for the same interface) and warning messages in batctl like this one:
> root@ql-oncelotes:~# batctl o
Warning - name already known (changing mac from 'F6:D5:91:7F:CA:D2' to '2e:37:8e:5d:32:e8'): si_monica_bat0
Warning - name already known (changing mac from '06:4B:C4:D4:89:50' to '46:f0:c8:89:16:00'): si_radio_bat0
Warning - name already known (changing mac from '76:0C:12:EB:D4:7E' to '46:d6:3b:16:e0:c2'): si_nestor_bat0
Warning - name already known (changing mac from '2E:37:8E:5D:32:E8' to '12:c1:ba:2b:9d:47'): si_monica_bat0 …
=> In bat-host take iface name as unique key

.travis.yml
I am not really knowledgeable about Travis or Docker, but I had a look at the causes of the [current failing](https://travis-ci.org/libremesh/lime-packages/builds/571877260) and I think it is happening because of a wrong directory name (in the [Docker image](https://hub.docker.com/r/openwrtorg/sdk), /home/build/sdk does not exist, /home/build/openwrt does) in the .travis.yml file.
=> Updated directory name inside Travis file

packages/lime-system/files/usr/lib/lua/lime/wireless.lua
In `wireless.lua` from `lime-system` package the [third line here](https://github.com/libremesh/lime-packages/blob/81168c1af02b76f079228d8d9d629d0369a4aad5/packages/lime-system/files/usr/lib/lua/lime/wireless.lua#L120-L124) can be safely removed:
```
if type(channel) == "table" then
local chanIndex = 1 + radioName:match("%d+$") % #channel
chanIndex = chanIndex > 0 and chanIndex or 1
channel = channel[chanIndex]
end
```
In Lua the `%` operator (in the second line) has always zero or positive output and [has the precedence](https://www.lua.org/manual/5.3/manual.html#3.4.8) over the `+` operator.
So `chanIndex` calculated in the second line will always be at least 1 and there is no need for the third line.
I cannot test as I don't own any router with more than one radio on the same band...
=> Remove unused line from wireless.lua

packages/ubus-lime-metrics/Makefile
ubus-lime-metrics package [employs netperf](https://github.com/libremesh/lime-packages/blob/master/packages/ubus-lime-metrics/files/usr/libexec/rpcd/lime-metrics#L77-L80) for measuring the bandwidth but netperf was not included between the dependencies.
=> Add netperf dependency to ubus-lime-metrics Makefile

packages/lime-system/tests/test_lime_wireless.lua, tests/fakes/iwinfo.lua, tests/test_iwinfo.lua
Should be applied after P4 (#565  ).
Hint: easer review doing commit by commit.
=> [Unittesting P5] fake iwinfo and wireless tests

libremesh.sdk.config, packages/bandwidth-test/Makefile, packages/bandwidth-test/files/bin/bandwidth-test.lua, packages/bandwidth-test/files/etc/config/bandwidth-test, packages/lime-debug/Makefile
This Lua script downloads a list of files from the internet (it could also be used for measuring the local network speed, but for this case using netperf like in [lime-metrics](https://github.com/libremesh/lime-packages/blob/ce7a73038afb5de5b7709e9bbfc353c97c86913e/packages/ubus-lime-metrics/files/usr/libexec/rpcd/lime-metrics#L77) would be more proper).
In order to not take too long on slow networks, the downloads are interrupted after a specific time (the SINGLE_TEST_DURATION option). This has the drawback that on fast connections, the SINGLE_TEST_DURATION time has to be waited even if the file download has already finished.
In my opinion this is not a problem, but if you want I can try to change this.
The final speed output is taken as the median of a few measurements on different …
=> bandwidth-test package for maximum available bandwidth towards the internet

.gitignore, .travis.yml, README.md
We recently enabled unitesting in LibreMesh. This small contribution incorporates a badge with the percentage of test coverage and the link to its analysis.
It also ignores the file luacov.stats.out that is generated when the tests run locally.
=> Add codcov env variable and badge

packages/lime-proto-anygw/files/usr/lib/lua/lime/proto/anygw.lua
This should cause more devices to set the correct MTU on their interface, as it rely on RA options that are usually taken in account more rigorously by clients confronted to DHCPv4 options. So it should improve user experience in general.
=> anygw push link MTU option also via RA

README.md
In the main Readme it is indicated that the repo lime-ng-ui must be added to the feeds list. This information is incorrect at the current stage of development. The required packages are already integrated into lime-packages.
=> Fix main readme

packages/lime-system/files/usr/lib/lua/lime/network.lua, packages/lime-system/tests/test_lime_network.lua, tests/test_lime_config_device.lua
Allow disabling or customizing the validation of the existance of the interfaces from the tests. Now mocking this in the tests instead of disabling the assertions globaly.
Tests are failing if run in a machine without `eth0` (not the case of travis nor my computer...)
=> Fix device tests

tools/dockertestshell
Without this change executing `./tools/dockertestshell` gives an error beacause `latest` tag does not exists as docker uses `latest` by default instead of using _any_ tag available (1.0 is available)
=> testshell: use docker explicit '1.0' tag instead defaulting to 'latest'

packages/bandwidth-test/files/bin/bandwidth-test.lua
Up to now, the help of bandwidth-test executable was printed just with `bandwidth-test bibidi babidi bu` but not with `-h` or `--help`. This recognized the special options `-h` and `--help` while it still ignores any non-numerical first and second arguments.
Fix #590
=> Help output in bandwidth-test, fix #590

packages/lime-system/files/usr/lib/lua/lime/network.lua, packages/lime-system/tests/test_lime_network.lua
Also added some tests to network.createVlanIface.
vlan=0 can be used to "disable the vlan" for a protocol. So using protocol `babel:0` disables the vlan.
=> createVlanIface fixes for vlan = 0

packages/lime-proto-anygw/Makefile
lime-proto-anygw is using ebtables functions (`--ip6-protocol`) which require a kernel module currently not included in its Makefile:
https://github.com/libremesh/lime-packages/blob/f5d680cf269f8ff109c39c639206e5283be9b52d/packages/lime-proto-anygw/files/usr/lib/lua/lime/proto/anygw.lua#L69-L74
=> adding kmod-ebtables-ipv6 to anygw dependencies

packages/lime-proto-babeld/files/usr/lib/lua/lime/proto/babeld.lua, packages/lime-system/files/usr/lib/lua/lime/network.lua, tests/test_lime_config_device.lua
This fixes #580 
Some of the other protocols have mtu configurations but not all for example olsr, bgp. So this is only fixing babel I don't know if we want to create a more general patch that always use MTU = 1496 when using ETH + VLAN.
I have tested this with two LibreRouters. LR-A connected through WAN to "internet". LR-B connected to LR-A with LAN port to LAN port of LR-A. In this scenario pinging from LR-B to internet with `ping -s SIZE 192.168.1.1` only works when `SIZE <= 1470`. With this fix size could be greater than 1470 without problem.
=> proto.babel: fix eth MTU when using vlan

packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw
This fixes the set_network step of firstbootwizard.
I introduced this bug in the refactor of fbw as a module. I tested all the functionality but through lua directly like 
```
fbw = require "firstbootwizard"
fbw.apply_file_config(...)
```
But I did not tested the calls through `/usr/libexec/daemon/lime-fbw`
One thing that we discovered debuging this is that If one function fails then the daemon dies. So a good idea is to use xpcall in all the calls though libexec.
=> fbw: missing namespace after module refactor

packages/lime-hwd-openwrt-wan/files/usr/lib/lua/lime/hwd/openwrt_wan.lua, packages/lime-hwd-openwrt-wan/tests/test_lime_hwd_openwrt_wan.lua, packages/lime-proto-babeld/files/usr/lib/lua/lime/proto/babeld.lua, packages/lime-system/files/usr/lib/lua/lime/network.lua, packages/lime-system/files/usr/lib/lua/lime/system.lua, packages/lime-system/files/usr/lib/lua/lime/wireless.lua, tests/test_lime_config_device.lua
utils.log is prefered because we can control its output for example
disabling writing to stdout when testing.
I removed all the prints that polluted the testing output, so I am confident that this is not breaking anything.
=> Logging intead of print

packages/lime-proto-bmx6/src/bmx6.lua, packages/lime-proto-bmx7/files/usr/lib/lua/lime/proto/bmx7.lua, packages/lime-proto-olsr/src/olsr.lua, packages/lime-proto-olsr2/src/olsr2.lua, packages/lime-proto-olsr6/src/olsr6.lua
Between the arguments which can be provided to the routing protocols, the first one is usually the VLAN ID.
Force it to be numeric, for all the protocols except Batman-adv one which can be parametrized with %N1 (and except Babeld which is being treated in #631).
=> protos: force vlanId to be numeric

packages/first-boot-wizard/files/bin/firstbootwizard, packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua, packages/first-boot-wizard/tests/test_firstbootwizard.lua, packages/lime-system/files/etc/config/lime-defaults, packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw
Fixes #569 
Also prevents FBW from running the scanning/network gathering at boot time if it is already configured.
=> FirstBootWizard use uci instead of /etc/first_run

packages/shared-state-persist/files/usr/bin/shared-state-persist
We are currently thinking about other automatic behaviors with storage devices in routers. With this pull-request the behavior of shared-state-persist is changed so that it ignores the device if it has a file with the name .shared_state_persist_ignore_device in the root.
=> Option to ignore devices in shared-state-presist

packages/lime-app/Makefile, packages/lime-app/files/96-lime-app-index_page, packages/lime-app/files/lime_app_index.html
Fixes #609 
The new index file used for redirection has been copied from LibreRouter's OpenWrt repository [here](https://github.com/LibreRouterOrg/openwrt/blob/d2282e29b0888dfa272149d845f48b202ec61b6f/files/www/index.html).
=> lime-app installs the redirect to /app

packages/pirania/Makefile
Running a LibreMesh image with installed `pirania` and `pirania-app` packages, I had some errors in logread:
```
daemon.err uhttpd[2640]: Could not open plugin uhttpd_lua.so: Error loading shared library uhttpd_lua.so: No such file or directory
daemon.info procd: Instance pirania-uhttpd::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
```
the file uhttpd_lua.so is part of the package uhttpd-mod-lua which I think should be included in the pirania package dependencies.
=> Add uhttpd-mod-lua dependency to pirania

packages/lime-proto-anygw/files/usr/lib/lua/lime/proto/anygw.lua
This fixes dnsmasq returning the anycast address when the dns query
is for a host if dnsmasq does not know about it. For example
pepe.thisnode.info was returning the anycast address if pepe was not
known by dnsmasq (or only the ipv4 was known and the ipv6 was
requested).
This started to bite after https://github.com/libremesh/lime-packages/pull/541
This is related to openwrt's:
```
dfea3bae11dd5c207182371ce1fdca763fb5bbe0
Author: Jo-Philipp Wich <jow@openwrt.org>
Date:   Mon Jun 17 11:55:30 2013 +0000
dnsmasq: use host-record instead of address
Using "--address" for individual host A records is broken, use
"--host-record" instead.
```
before the fix:
```
$ dig +noall +answer  A @nodo2 bonzo
bonzo.            0    IN    A    10.133.xxx.204
$ dig +noall +answer AAAA @nodo2 bonzo
$ dig …
```
=> anygw: use dnsmasq host-record instead of address

packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
Use OPENWRT_ARCH with a fall back to LEDE_ARCH, this add support to 19.07 with backward compatibility.
=> uci-defaults: make 92_add-lime-repos compatible with 19.07

packages/lime-report/files/lime-report.sh
The AP passwords are shown also by the `wifi status` command, so the filter for not disclosing passwords have to be applied also to the commands output.
=> lime-report filter keys also in commands

packages/lime-docs/files/lime-example, packages/lime-system/files/usr/lib/lua/lime/wireless.lua
I some rare cases can make sense to decrease the output power of wireless radios.
This PR adds the possibility to set the txpower both globally (makes sense only for single-radio routers) or specifically for each wireless radio.
=> Add txpower option for wireless radios

packages/lime-system/files/usr/lib/lua/lime/wireless.lua
Currently, if a specific wireless interface configuration is used but no mode is specified, `lime-config` fails due to indexing of a nil value in `if modes[1] ~= "manual" then` introduced in https://github.com/libremesh/lime-packages/commit/d4f7a8c2bf20a373854c1f796dec9f9916642bbb.
Even if it was not failing, I think that a specific interface configuration without any mode does not make much sense. So now, if no mode is specified, the general ones are used.
=> Specific wireless interface: if no mode is configured, use default ones

packages/lime-system/files/usr/lib/lua/lime/utils.lua, packages/lime-system/tests/test_lime_utils.lua
We have multiple shell() functions all over the code and in some places the use is not safe. Let's face that it is a very handy practice but let's do it "safe". So I propose to add a new `utils.unsafe_shell()` function. The idea of having the unsafe word in its name is to encourage the developer of taking it carefully. 
Also adding `utils.shell_quote()` that is based on Python's shlex.quote(). Using unsafe_shell + shell_quote may be considered "safe".
After this PR is merged I will push changes to replace the actual shell calls by this new functions.
=> utils: adds unsafe_shell() and shell_quote() functions

packages/ubus-lime-metrics/files/usr/libexec/rpcd/lime-metrics
this pull-request tries to fix the get_gateway method in "lime-metrics". I'm using the last_internet_path file to get the last value and return it as the gateway. 
I also added a try catch statement to verify that the last_internet_path file exists and doesn't crash.
=> Fix metrics (gateway detection)

packages/lime-docs/files/lime-example, packages/lime-proto-batadv/files/usr/lib/lua/lime/proto/batadv.lua, tests/test_lime_config_device.lua
See the discussion on #676
This PR is an alternative to #676 
Retrocompatibility with the previous release is not going to happen anyway, so this keeps the retrocompatibility just for the users using development code.
At the price of a bit more weird way to calculate the VLAN ID.
=> lime-proto-batadv VLAN ID start from 20 rather than from 16 and keep old default VLAN ID

CONTRIBUTING.md
We are no longer using `develop` branch, instead we use the `master` branch.
=> update CONTRIBUTING with current branching practices

packages/lime-app/Makefile
This PR bumps limeapp version from v0.2.3 to v0.2.5, please check [CHANGELOG](https://github.com/libremesh/lime-app/blob/develop/CHANGELOG.md) for details
=> LimeApp updated to v0.2.5

packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua, packages/first-boot-wizard/tests/test_firstbootwizard.lua, packages/lime-system/files/usr/lib/lua/lime/utils.lua, packages/lime-system/tests/test_lime_utils.lua, packages/ubus-lime-fbw/README.md, packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw, packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils-admin, packages/ubus-lime-utils/files/usr/share/rpcd/acl.d/lime-utils-admin.json, packages/ubus-lime-utils/tests/test_lime_utils_admin.lua
Allow  the creation of a network with a shared community admin password
Also `fbw.apply_user_configs(configs. hostname)` is changed by a clearer `fbw.create_network(ssid, hostname, password)`
This is to be applied on top of PR #700 , so only the last few commits are new to review.
=> FBW community shared password network creation

packages/lime-proto-batadv/files/usr/lib/lua/lime/proto/batadv.lua, packages/lime-proto-batadv/tests/test_batadv.lua
commit openwrt-routing/packages@54af5a209e0a
("batman-adv: Split batadv proto in meshif and hardif part") changed the
way batman-adv is configured in OpenWrt. Change the lime proto accordingly.
This is needed for lime-proto-batadv to work with OpenWrt 19.07 or newer.
Signed-off-by: Daniel Golle <daniel@makrotopia.org>
=> proto-batadv: adapt to new UCI API

packages/lime-system/files/usr/lib/lua/lime/wireless.lua
802.11b uses 22MHz channels with CCK modulation which causes significant noise on neighbouring 20MHz channels as they are partially overlapping.
Disabling CCK allows for better spectrum utilization as can then use 4 non-overlapping 20MHz channels (1,5,9,13) instead of just 3 (1,6,11) when located within ETSI regulatory domain.
Using `'not wireless.is5Ghz(radioName)` to designate potential 802.11b radios may not cover all cases (dual-band radios, other not yet supported non-5GHz-bands such as 60GHz)... But does the trick for all classic routers.
=> wireless: add option legacy_rates to allow disabling 11b rates

packages/lime-docs/files/lime-example
This PR updates `lime-examples` to address this issue in **lime-web**: [clarify ssid prefixes](https://github.com/libremesh/lime-web/issues/60).
That issue was partly resolved in [this PR in lime-web](https://github.com/libremesh/lime-web/pull/109).
=> Update SSID documentation in lime-example

packages/lime-proto-bmx6/Makefile, packages/lime-proto-bmx7/Makefile
conditional dependencies are deprecated. create hard dependency instead as it seems the only good solution.
=> bmx6/7: unconditionally depend on ebtables

packages/lime-docs/files/lime-example, packages/lime-proto-bmx7/files/usr/lib/lua/lime/proto/bmx7.lua, packages/lime-system/files/etc/config/lime-defaults
To make use of bmx7 signature checking one has to set
`bmx7.general.trustedNodesDir='/etc/bmx7/trustedNodes'`
Allow communities to do that by reading the value from lime's
`network.bmx7_trustedNodesDir` option.
Signed-off-by: Daniel Golle <daniel@makrotopia.org>
=> bmx7: allow setting trustedNodesDir

packages/lime-proto-batadv/Makefile, packages/lime-proto-batadv/files/usr/lib/lua/lime/proto/batadv.lua, packages/lime-proto-batadv/tests/test_batadv.lua, packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
This PR re-enable batman-adv meshing over ethernet, this solve bla2 loops when nodes sees each other both via ethernet and wifi, the log flooding is avoided changing the mac-address of the vlan, this trick didn't worked in the past as the unicast packets never arrived to the vlan interface as they were probably sucked in by the bridge on top of the plain ethernet interface.
I have been testing this for a few days in a real network with 9 devices distributed across 3 houses with plenty of nodes which see each other both over cable and over WiFi, no loops observed and no log flooding either. Finally!
=> Batman-adv enable meshing over ethernet replaces #703 #724

packages/shared-state/Makefile, packages/shared-state/files/usr/lib/lua/shared-state.lua
luci-lib-httpclient pulls in 200kB of dependencies.
Replace it with a wrapper around uclient-fetch.
Fixes #720
(I'm not much of a Lua hacker...)
=> shared-state: use uclient-fetch instead of luci-lib-httpclient

packages/lime-app/Makefile
This was missing from f4f8d004ff8564452ab705b02687eff9cc063334
=> lime-app: fix missing files in package

packages/lime-system/files/usr/lib/lua/lime/utils.lua, packages/lime-system/tests/test_lime_utils.lua, packages/safe-upgrade/Makefile, packages/safe-upgrade/files/usr/sbin/safe-upgrade, packages/safe-upgrade/tests/test_safe-upgade.lua, run_tests, tests/test_test_utils.lua, tests/utils.lua
Many improvements in safe-upgrade! This changes allows to expose better a firmware upgrade mechanism through ubus.
* upgrade now reboots  after upgrade (add `--no-reboot`), just like sysupgrade.  Rebooting right away after upgrading is almost always what the user want to do.
* improved upgrade backup functionality adding `--preserve-archive` option to the upgrade (like `sysupgrade -f`). By default uses config 'lime.keep_on_upgrade' to provide the list of files to preserve.
* remove short option `-f` (as this means something else in sysupgrade it may lead to confusion)
* add `verify` cmd to veryfy of a firmware (like `sysupgrade --test`)
* add `board_supported` subcommand (to be able to ask the firmware if safe-uppgrade can be performed or a fallback to sysupgrade has to be used)
* …
=> safe-upgrade improvements

.dockerignore, Dockerfiles/Dockerfile.unittests, packages/safe-upgrade/tests/test_safe-upgade.lua, run_tests, tools/dockertestshell
Unittests are broken from #737 . I don't know how github allowed merging without a green status after the last push, or maybe travis did not run at each push.
This fixes this.
Also changes the behaviour of ./run_tests to use docker pull instead of docker build. This speed things up in  the first use.
=> Fix unittests broken and use docker pull instead of local build

packages/shared-state-nodes_and_links/Makefile
shared-state-nodes_and_links [here](https://github.com/libremesh/lime-packages/blob/38ceff23454141b67981686d484e6c2b33ee20ae/packages/shared-state-nodes_and_links/files/usr/bin/shared-state-publish_nodes_and_links#L29) uses a file provided by ubus-lime-location [here](https://github.com/libremesh/lime-packages/blob/master/packages/ubus-lime-location/files/usr/libexec/rpcd/lime-location) so it looks like it has to depend on ubus-lime-location.
=> shared-state-nodes_and_links add dependency from ubus-lime-location

packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
When we started using limewireless.mesh_ifaces() we broke the expected api.
This adapt lime-utils.get_node_status to the new api and recover most_active in the response
=> lime-utils: fix get_node_status most_active field

packages/lime-system/files/usr/bin/mac2ipv6ll, packages/lime-system/files/usr/lib/lua/lime/utils.lua, packages/lime-system/tests/test_lime_utils.lua, packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
Use our own implementation of the conversion of mac to ipv6linklocal to workarround this bug in luci.ip.tolinklocal https://github.com/openwrt/luci/pull/4415
Also provided is the utility script `mac2ipv6ll`
=> Fix shared-state get candidates neigh

packages/check-internet/Makefile, packages/check-internet/files/usr/bin/check-internet
uclient-fetch is used by opkg and other core utilities.
=> check-internet: use uclient-fetch instead of wget

packages/luci-app-lime-location/files/usr/lib/lua/luci/controller/location.lua
I casually found a typo in luci-app-lime-location package
=> luci-app-lime-location fix typo

packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
Thanks to @aparcar and @spiccinini now we have again a binary repository.
This sets its location in the firmware so that OPKG can use it.
Fix #767
=> Set LibreMesh packages repository location

packages/lime-system/files/usr/bin/lime-sysupgrade
Fix #769 
Here goes three changes to lime-sysupgrade script from lime-system package:
1) when one of the files from a collection was missing, for example /root/.ssh/known_hosts from dropbear collection, a misleading warning was printed, for example:
`Warning: Cannot read /lib/upgrade/keep.d/dropbear file`
even if `/lib/upgrade/keep.d/dropbear` exists.
2) the checksums since OpenWrt 19.07 are SHA256 by default, so I added the output of sha256sum. I think that sha256sum was not present in OpenWrt 18.06, so I added a check for its presence.
3) in case the router was not supported by safe-upgrade (or did not have installed it), a broken check caused the lack of preservation of the configuration.
=> Improvements to lime-sysupgrade

packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
Sorry for not thinking this before but we can add also the packaged network-profiles repository to OPKG available packages.
Then, in order to install a network profile using OPKG it could be necessary to use the `--force-overwrite` option from `opkg` command. This is needed only for profiles providing files already existing in the router (like [this](https://github.com/libremesh/network-profiles/tree/master/libremesh/default/root/etc/config)) but will not be needed for some other network-profiles which set the options in other ways (like [this](https://github.com/libremesh/network-profiles/tree/master/libremesh/encrypt-11s/root/etc/uci-defaults)).
See also discussion on #747
=> Add network-profiles packages repo to OPKG feeds

tools/qemu_dev_start
Fixes a bug when creating the rootfs when `--libremesh-workdir` is used and checks for the interfaces before its creation
=> Some Qemu fixes

packages/lime-app/Makefile
This version includes fixes for limeapp crashing whe ubus-lime-fbw is not available, and privilege escalation through firstbootwizard.
It should be merged along with #791
=> LimeApp updated to v0.2.10

packages/ubus-lime-fbw/files/usr/share/rpcd/acl.d/lime-fbw.json
This PR changes acl for firstbootwizard, in order to fix the current privilege escalation reported at: https://github.com/libremesh/lime-packages/issues/763#issuecomment-696670006
It should be merged along with https://github.com/libremesh/lime-app/pull/277 at the LimeApp
=> firstbootwizard: now needs root privilege to run

packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua, packages/first-boot-wizard/tests/test_firstbootwizard.lua, packages/lime-docs/files/www/docs/lime-example.txt, packages/lime-system/files/etc/config/lime-defaults, packages/ubus-lime-fbw/files/usr/libexec/daemon/lime-fbw, packages/ubus-lime-fbw/files/usr/share/rpcd/acl.d/lime-fbw.json
This PR adds the ability to dismiss fbw from an ubus endpoint, which will be called by the LimeApp. Addressing #786 
The corresponding PR in the limeapp side is https://github.com/libremesh/lime-app/pull/278
Comments and suggestions about the implementation are welcomed. I thought it would be nice to keep track of whether the fbw has been performed firstbootwizard_configured=true or it has been dismissed firstbootwizard_dismissed=true.
Also, when dismissing, the config option is not reloaded until a reboot or restart of the rpcd service, so a temp file is used to reflect the dismiss too.
Disclaimer: This branch is rebased with the one of #791. They introduce changes in the same acl
=> Fbw add dismiss option

packages/ubus-lime-utils/files/etc/profile.d/system_notes.sh, packages/ubus-lime-utils/files/etc/profile.d/ubus-lime-utils-system_notes.sh
With #784 I created a conflict with the (abandoned) lime-webui package.
See the report on https://lists.libremesh.org/pipermail/lime-users/2020-October/001737.html
I also changed the indication of how to modify the node from lime-app (including the full URL).
=> Renamed ubus-lime-utils' system_notes.sh to avoid conflicts with lime-webui

packages/lime-proto-bgp/Makefile
Fix #645
This will remove the Warning (it is not an Error!!!) from the compilation with OpenWrt 19.07 but will add the warning to the compilation with OpenWrt 18.06. I have no idea how to write a dependency valid both for OpenWrt 18.06 and 19.07 without using conditional dependencies which are evil (see #331 #673 ).
Here you can find the [Bird Makefile in 18.06](https://github.com/openwrt-routing/packages/blob/openwrt-18.06/bird/Makefile) and the [Bird1 Makefile in 19.07](https://github.com/openwrt-routing/packages/blob/openwrt-19.07/bird1/Makefile).
Plenty of users were alarmed by this warning (DrivenMadz on IRC/Element, #750, #645, on the ML [here](https://lists.libremesh.org/pipermail/lime-users/2020-August/001657.html), [here](https://lists.libremesh.org/pipermail/lime-users/2020-Augus …
=> lime-proto-bgp depend on bird1-* packages from OpenWrt 19.07

packages/lime-report/files/lime-report.sh
There were two errors in the capture of the dmesg output in lime-report utility: tail was using -c option instead of -n and the fact that the command included a pipe made necessary to enclose the command in quotes.
=> lime-report fix dmesg command and add info on firewalls

packages/lime-proto-babeld/files/usr/lib/lua/lime/proto/babeld.lua
See issue description in #788.
In #788 two issues are described, the second one is addressed here.
=> babeld: do not forcefully enable libremap plugin

packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua
wget path changed from 18.06 to 19.07 so this is to be more compatible.
Current uses of firstbootwizard (init.d and ubus daemon) have the PATH
env variable correctly populated so this should not break anything.
Fixes #798
=> fbw: use non absolute wget path

packages/pirania/files/etc/init.d/pirania-dnsmasq
Right now, /etc/dnsmasq.conf points to /etc/dnsmasq.d/,
which contains lime-proto-anygw-20-ipv6.conf and makes
pirania-dnsmasq do IPv6 router-advertisements on br-lan and anygw
very confusing and totally unrelated to pirania-dnsmasq function
=> pirania: pirania-dnsmasq should not read /etc/dnsmasq.conf

packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua, packages/first-boot-wizard/files/www/cgi-bin/lime/lime-community, packages/first-boot-wizard/files/www/lime-community
Sharing the lime-community file as a symlink needs read permissions and uci changes these file permissions in 19.07 when uci commit is run.
Sharing the file as a cgi-bin prevents this problems and is also more hackable. 
Fixes #807
=> fbw: share lime-community as cgi-bin

packages/lime-app/Makefile
Now that lime-app does not depend on libremap/luci I've spoted some missing dependencies. If we dont  select rpcd then there is a circular dependency and lime-app can't be selected:
```
tmp/.config-package.in:955:     symbol PACKAGE_rpcd is selected by PACKAGE_attendedsysupgrade-common
tmp/.config-package.in:7:       symbol PACKAGE_attendedsysupgrade-common is selected by PACKAGE_luci-app-attendedsysupgrade
tmp/.config-package.in:74090:   symbol PACKAGE_luci-app-attendedsysupgrade depends on PACKAGE_uhttpd
tmp/.config-package.in:132131:  symbol PACKAGE_uhttpd is selected by PACKAGE_lime-app
tmp/.config-package.in:73092:   symbol PACKAGE_lime-app depends on PACKAGE_rpcd
```
=> Fix some Lime-App dependencies

.github/workflows/build.yml
Hopefuly fIxes github action.
I am not exactly sure but as per the following documentation  https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files this should do the work.
=> github-ci: replace deprecated set-env

packages/lime-ap-watchping/Makefile
lime-ap-watchping edits `lime-autogen` [here](https://github.com/libremesh/lime-packages/blob/38ceff23454141b67981686d484e6c2b33ee20ae/packages/lime-ap-watchping/files/etc/uci-defaults/91_autoAP#L2-L3) and get configs from `lime` [here](https://github.com/libremesh/lime-packages/blob/3e7573c4936bb0851f045af06513aba6489ddcb0/packages/lime-ap-watchping/files/etc/init.d/auto-ap#L10) (which I suppose will fail as it does not exist anymore?) so it is evident that has to depend on `lime-system`.
=> lime-ap-watchping add dependency from lime-system

packages/ubus-lime-utils/files/usr/lib/lua/lime/upgrade.lua
Fixes the get_upgrade_info ubus endpoint, broken by the intrusion of the print into the json output.
=> lime-utils: remove debugging print

packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
make `shared-state` aware of interfaces used by babeld, and search for candidate neighs in those interfaces as well.
=> shared-state: parse babeld.conf interfaces in get_candidates_neigh

packages/lime-debug/Makefile, packages/shared-state/Makefile, packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh, ping6retrocompat.mk
As busybox ping6 doesn't support float intervals, ping6 from iputils is needed, in recent versions of OpenWrt the package iputils-ipv6 has been removed and meld into iputils-ping, the output of the command also changed son a few tricks to keep compatibility with all this different versions were needed.
As a bonus also lime-debug get its dependencies fixed for OpenWrt master in a retro-compatible way.
=> shared-state: multiple fixes

.github/workflows/tests.yml, .travis.yml
Also disable coverage in travis.
After this PR is merged we have all the CI functionality, that we had with travis, in github-ci. So I will open another PR after this is merger to disable travis completly.
=> Add unittests with coverage to GitHub-CI

packages/lime-proto-babeld/files/usr/lib/lua/lime/proto/babeld.lua
right now, babeld doesn't route between clouds over ipv6, since `main_ipv6_address` is set to `fd%N1:%N2%N3:%N4%N5::/64`
also, conceptually it makes total sense to redistribute `fc00::/7` the same way `10.0.0.0/8` is redistributed
=> Lime proto babeld fixes

libremesh.mk, packages/eupgrade/Makefile, packages/lime-proto-babeld/Makefile, packages/lime-proto-batadv/Makefile, packages/lime-proto-bmx6/Makefile, packages/lime-proto-bmx7/Makefile, packages/lime-proto-wan/Makefile, packages/lime-smart-wifi/Makefile
The idea is to be able to use libremesh.mk like a module so that it can be more easily customized.
I still have to test a full build with this, but want to share the idea to get feedback.
Fixes #825
=> Refactor libremesh.mk and makefiles

libremesh.sdk.config, packages/lime-app/Makefile, packages/lime-app/files/usr/share/rpcd/acl.d/iwinfo.json, packages/lime-system/files/usr/lib/lua/lime/utils.lua, packages/lime-system/tests/test_lime_utils.lua, packages/shared-state-bat_hosts/files/usr/lib/lua/bat-hosts.lua, packages/shared-state-bat_hosts/files/usr/libexec/rpcd/bat-hosts, packages/shared-state-bat_hosts/files/usr/share/acl.d/bat-hosts.json, packages/shared-state-bat_hosts/tests/test_bat_hosts.lua, packages/shared-state-bat_hosts/tests/test_ubus_bat_hosts.lua, packages/ubus-lime-openairview/Readme.md, packages/ubus-lime-openairview/files/usr/libexec/rpcd/lime-openairview, packages/ubus-lime-utils/Makefile, packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
This PR introduces the v0.2.15 of the LimeApp, We have skipped v0.2.11 through v0.2.14 so all the new changes are:
firmware upgrade: add one click firmware upgrade
firstbootwizard: add do not ask again option to fbw banner
align: New align screen
remotesupport: Add support for handling and joining tmate sessions.
for more info checkout the [changelog](https://github.com/libremesh/lime-app/blob/develop/CHANGELOG.md)
The new align screen uses rpcd-mod-iwinfo ubus endpoints instead of lime-openairview.
All the functionality of lime-openairview except of spectral scan is removed. Which breaks compatibility with prior lime-app versions. That's why this PR includes changes + release bump altogether.
=> New align screen

packages/first-boot-wizard/files/usr/lib/lua/firstbootwizard.lua, packages/first-boot-wizard/files/www/cgi-bin/lime/lime-community-assets
The lime-assets are documented here https://libremesh.org/docs/en_config.html#lime-assets
This PR only adds the lime-assets support to fbw.
The lime-assets of level community are shared as a tar.gz and fetched as part of the first boot wizard config step.
Fixes #846
=> fbw: support community lime-assets

packages/shared-state-nodes_and_links/files/usr/bin/shared-state-publish_nodes_and_links, packages/ubus-lime-location/tests/test_lime_location.lua
At https://github.com/libremesh/lime-packages/pull/834 we have broken the shared state publisher for nodes_and_links.
The broken version would publish an entry for each field (links, hostname, macs, etc) in shared-state db, breaking the non-robust lime-app ui for the map.
=> Fix shared state location publisher

packages/ubus-lime-utils/files/usr/lib/lua/lime/upgrade.lua, packages/ubus-lime-utils/tests/test_lime_utils_admin.lua
If no preserve config option is passed (`preserve_config = nil`) then preserve the config instead of not preserving it. This semantic matches better the sysupgrade semantic.
As in the last lime-app release there is no longer a preserve config checkbox, this change enforces (fixes) the intended behaviour of preserving the config instead of not doint it.
=> lime-utils: on upgrade preserve configs by default

packages/lime-app/Makefile
New version of LimeApp
* **align:** url incremental growth at align-single ([3f92f6a](https://github.com/germanferrero/lime-app/commit/3f92f6a5079143c1b6478b0d1ab3483076d642db))
* **firmware:** fix firmware upgrade when eupgrade is missing ([f6683af](https://github.com/germanferrero/lime-app/commit/f6683af2a36c33a9d67a43824a46d8eb419667f1))
* **i18n:** fix localization fallback. Bring back some PT-br translations([4891d66](https://github.com/germanferrero/lime-app/commit/4891d666c810623980c36d6ee2dae32a6462a8d3))
* **remotesupport:** fix remotesupport broken ui when no internet ([a198536](https://github.com/germanferrero/lime-app/commit/a19853687e21aef94b3809ff4155e07a28a1f958))
* **changenode:** improve UI texts with more user-friendly ones …
=> LimeApp updated to v0.2.16

ping6retrocompat.mk
Fixes https://github.com/libremesh/lime-packages/issues/863
=> ping6retrocompat.mk: use grep instead of relying in git history

packages/ubus-tmate/files/usr/lib/lua/tmate.lua
Tmate shows an initial screen like this:
For a recently created session, but only for ssh/terminal clients, in the web client (as in the LimeApp) a black screen is shown instead.
By sending CTRL + c right after opening the session, that screen is not shown anymore, and both ssh/terminal and web clients see the Libremesh Banner and the prompt when joining.
=> Fix tmate black screen when joining

.github/workflows/build.yml
Fixes #888
Hi @ilario, I have made the changes as discussed in https://github.com/libremesh/lime-packages/issues/888#issuecomment-889988221. 
Let me know if this needs any changes.
Thanks
=> add tail command to remove first character of the string

packages/lime-system/files/usr/lib/lua/lime/wireless.lua, packages/ubus-lime-utils/files/usr/lib/lua/lime/wireless_service.lua, packages/ubus-lime-utils/files/usr/libexec/rpcd/wireless-service, packages/ubus-lime-utils/files/usr/libexec/rpcd/wireless-service-admin, packages/ubus-lime-utils/files/usr/share/rpcd/acl.d/wireless_service.json, packages/ubus-lime-utils/tests/test_ubus_wireless_service.lua, packages/ubus-lime-utils/tests/test_wireless_service.lua
This PR is rebased with the branch of this PR: https://github.com/libremesh/lime-packages/pull/896
Please review that one first.
It adds ubus endpoints for enabling/disabling the ap mode in 2ghz radios.
And for setting up a wifi password for the apname mode in 2ghz radios.
This serves as a backend for a UI in the LimeApp to do the same.
=> Allow changing wifi password

packages/lime-proto-anygw/files/usr/lib/lua/lime/proto/anygw.lua
If a system domain is being configured use it as a domain for this
router by configuring the DNS hostrecord to use it together with
thisnode.info and minodo.info.
=> lime-proto-anygw: use the configured domain as a hostrecord

packages/ubus-lime-location/files/usr/lib/lua/lime/location.lua, packages/ubus-lime-location/tests/test_lime_location.lua
location.set() was inserting bad keys to nodes_and_links database.
This bug made the community view in the map unavailable until the TTL for these bad keys reach 0 due to parsing errors.
=> location: fix set() inserting bad data to shared-state

packages/watchping/files/usr/bin/watchping
Currently, *-ok hooks run when ping success after the daemon has started,
but *-fail hooks don't in the case that the ping keep failing until timeout .
With this change, the same logic is applied for both cases: success and failure.
=> watchping: change starting value for last_hook_run

packages/lime-system/files/lib/upgrade/keep.d/libremesh
Currently when upgrading with lime-sysupgrade banner.notes is lost. Let's add it to libremesh's keep.d
=> keep.d: add banner.notes

packages/lime-app/Makefile, packages/lime-app/files/etc/uci-defaults/90_lime-app, packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils-admin
We have been testing a new version of limeapp v0.2.25 in different communities, and it is working well.
This PR also add two small fixes needed by this new version.
=> Lime app to version v0.2.25

packages/shared-state/files/www/cgi-bin/shared-state, packages/shared-state/files/www/cgi-bin/shared-state-multiwriter
Add compression support to the public synchronization endpoints so that the data is transmitted and received using gzip when `gzip` is part of the URL query-string. 
Why? mainly to help shared-state syncing when there is a bad quality link (low signal, too crowded airspace, etc) reducing the amount of packets that have to be transmitted. Also this leads to reduced bandwidth usage.
This change in its own does not change the current behaviour (uncompressed) but allows to use this feature in the future. There are two main possible mechanisms with different backwards compatibility policy:
1. Provide a backwards compatible mechanism that allows a node to know if the other node supports gzip or not and use the new endpoint in that case. There are many options to do this but all add complexity. …
=> shared-state: provide compressed cgi-bin endpoints

packages/lime-proto-babeld/files/usr/lib/lua/lime/proto/babeld.lua, packages/lime-proto-batadv/files/usr/lib/lua/lime/proto/batadv.lua, packages/lime-system/files/usr/lib/lua/lime/network.lua
Address recent bug discovered in Quintana Libre with eth1.2 LibreRouter interface being ignored when specific configuration section for it is needed.
=> Relax switch vlan filter

packages/lime-system/files/usr/lib/lua/lime/network.lua
=> network.lua use an alternate string if ifname is not found by owrt_device_parser

packages/lime-app/files/etc/uci-defaults/99-lime-app-update-title
Append a sed command to lime-apply that update the tag <title> in /www/app/index.html
to allow users to save the lime-app page of their device as a bookmark in the browser, without having to manually override the default title Lime.
I thought it was better to use a single sed command through an uci-default script instead of adding another dependency to lime-app itself, like https://www.npmjs.com/package/react-helmet to manage headers.
=> lime-app: update title in lime-app

packages/ubus-lime-utils/files/usr/lib/lua/lime-utils.lua, packages/ubus-lime-utils/files/usr/libexec/rpcd/lime-utils
This should fix https://github.com/libremesh/lime-packages/issues/962 . This fix some errors after https://github.com/libremesh/lime-packages/pull/939
=> Fix/lime utils issue #962

packages/wifi-unstuck-wa/files/usr/lib/lua/wifi_unstuck_wa.lua, packages/wifi-unstuck-wa/tests/test_wifi_unstuck.lua
Modification of wifi_unstuck_wa.lua so that it sends SIGTERM to all iw-processes still running after 5 minutes.
Fixes #964
=> unstuck-wifi: send SIGTERM to iw-processes still running after 5 minutes

packages/shared-state-dnsmasq_leases/files/usr/bin/shared-state-publish_dnsmasq_leases
Fix #969
I still have to test the modified code.
@pony1k can you test this?
=> shared-state-publish_dnsmasq_leases recognize IPv6 when IPv6 leases are present

packages/lime-system/files/usr/lib/lua/lime/network.lua
Fix #970
This is identical to #971 but without the commits that would be needed for fixing batman-adv-auto-gw-mode.
batman-adv-auto-gw-mode is severely outdated and will likely be archived, see #977
Please consider merging.
=> dnsmasq move confdir setting for ujail, avoiding to fix batman-adv-auto-gw-mode

packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
This removes the empty lines from the output of `shared-state-get_candidates_neigh` so that shared-state does not try to contact empty addresses (that causes the error shown below).
```
Failed to send request: Operation not permitted
```
=> shared-state get neigh avoid outputting empty lines

packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
When installing shared-state without Babeld, the following error appears every time shared-state is used:
```
grep: /var/etc/babeld.conf: No such file or directory
```
I tested the proposed change and executes the code only if that file is present.
Tell me if you prefer I open also an issue on this.
=> shared-state check for babeld file existence before reading it

packages/lime-hwd-openwrt-wan/files/usr/lib/lua/lime/hwd/openwrt_wan.lua, packages/lime-proto-wan/files/usr/lib/lua/lime/proto/wan.lua, packages/lime-system/files/usr/lib/lua/lime/network.lua, packages/lime-system/files/usr/lib/lua/lime/proto/lan.lua, packages/lime-system/files/usr/lib/lua/lime/utils.lua
See #951 
Specifically, here I tried to address two big differences that can be spotted in the reports attached in #951:
* the fact that with current code and when DSA is present, bat0 interface was not being added to br-lan bridge, see #958
* the fact that with current code and when DSA is present, eth0 was selected for addition to the bridge
* the fact that with current code and when DSA is present, the VLAN interfaces from the ethernet ports were not added inside bat0
On the last point, there are two big doubts:
* with DSA, eth0.1 does not exist anymore and has been replaced by lan1, lan2, lan3... So which interfaces should be created and added to bat0? I decided to create a VLAN for each of these, for example lan1_29, lan2_29, lan3_29...
* why the WAN interface was added to bat0? With …
=> Replace OpenWrt 19.07 switch config style with OpenWrt 21.02 one in proto-lan and network.lua's device parser

packages/lime-proto-babeld/files/usr/lib/lua/lime/proto/babeld.lua
Makes it easier to debug and allows the usage of luci-app-babeld
=> lime-proto-babeld: enable ubus bindings

packages/ubus-lime-utils/files/usr/lib/lua/lime-utils.lua, packages/ubus-lime-utils/files/usr/lib/lua/lime/node_status.lua, packages/ubus-lime-utils/tests/test_ubus_lime_utils.lua
Improve get node status results with following improvements:
- Split and refactor the code to be more atomic and redeable
- Add chain information to the result:
```json
"signal":  -14,
"chains": [
-17,
-16
],
```
- It also add information of the switch status (port, role, interface and link up or down). 
To get the switch status it combine the parsing of `/etc/board.json` to get the roles and `swconfig dev switch0 show` to get if they are up or not. The switches connected directly yo the cpu doesn't have a role attribute on the `/etc/board.json` so they are discarded. 
Using `ubus call lime-utils get_node_status '{}'`
```json
{
"ips": [
{
"version": "4",
"address": "10.219.123.10/16"
},
{
"version": "6",
"address": "fddb:f81c:47ba::a7b:be00/64"
},
{
"version": "6",
"address": …
```
=> Improve get node status results

packages/lime-proto-anygw/files/usr/lib/lua/lime/proto/anygw.lua, packages/lime-system/files/usr/lib/lua/lime/network.lua, packages/shared-state-dnsmasq_hosts/files/usr/bin/shared-state-generate_dnsmasq_hosts, packages/shared-state-dnsmasq_servers/Makefile, packages/shared-state-dnsmasq_servers/files/etc/shared-state/hooks/dnsmasq-servers/generate_dnsmasq_servers, packages/shared-state-dnsmasq_servers/files/etc/shared-state/publishers/shared-state-publish_dnsmasq_servers, packages/shared-state-dnsmasq_servers/files/etc/uci-defaults/shared-state-dnsmasq_servers, packages/shared-state-dnsmasq_servers/files/usr/bin/shared-state-generate_dnsmasq_servers, packages/shared-state-dnsmasq_servers/files/usr/bin/shared-state-publish_dnsmasq_servers
* a uci-defaults script points dnsmasq to use `/var/shared-state/dnsmasq_servers` as `servers-file`
* each node then publishes through shared-state their own dhcp.dnsmasq.domain and anygw ipv6
* each node populates the local `/var/shared-state/dnsmasq_servers` with all the domains and ipv6s from the other clouds.
=> shared-state-dnsmasq_servers: new package

packages/lime-system/files/usr/lib/lua/lime/network.lua
From OpenWrt 19.07 to 21.02, the content of `/etc/config/wireless` did not change (except #997) but the content of interfaces and devices in `/etc/config/network` changed significantly.
Inside lime-system's network.lua, the owrt_ifname_parser was used both for parsing `wifi-iface` from  `/etc/config/wireless` and for `interface` from `/etc/config/network`.
In this yet-to-be-tested code, I added a new section for probing only the interfaces from `/etc/config/networks`.
Also, I removed the "compound interface" code from owrt_ifname_parser as I suppose this was needed for br-lan, that now passed from being an `interface` to a `device` and so is taken care by owrt_device_parser.
=> Split network.lua's owrt_ifname_parser

packages/lime-proto-batadv/files/usr/lib/lua/lime/proto/batadv.lua, packages/lime-proto-batadv/tests/test_batadv.lua
The support for the new configuration style for Batman-adv has been introduced in https://github.com/libremesh/lime-packages/commit/fed6a468257ac461a4c81b16ac3361a36e7d3bde
Here I remove the new configuration style.
I did not test yet, but the edit is simple enough that I hope I didn't break anything.
=> lime-proto-batadv remove retrocompatibility

packages/lime-docs/files/www/docs/lime-example.txt, packages/lime-proto-batadv/files/usr/lib/lua/lime/proto/batadv.lua, packages/lime-proto-batadv/tests/test_batadv.lua, packages/lime-system/files/etc/config/lime-defaults
This is a first step for #1009 
By default, here BATMAN_IV is still selected.
=> Batman-adv allow the user to set the routing_algo

packages/lime-debug/Makefile
iperf3 is useful for checking the bandwidth of cabled or wireless connections
https://openwrt.org/packages/pkgdata/iperf3
jq is useful for reading directly the JSON files, like the ones from shared-state
https://openwrt.org/packages/pkgdata/jq
=> lime-debug added iperf3 and jq

packages/lime-report/files/lime-report.sh
The ubus bindings for Babeld have been activated in #987 
https://openwrt.org/docs/guide-user/services/babeld#ubus_bindings
The old `echo dump | nc ::1 30003` command has an additional output regarding the included interfaces, that I could not get from ubus, so I did not remove it.
Also, the errors from logread are included.
=> Added a few commands to lime-report

packages/check-date-http/Makefile, packages/check-date-http/files/etc/uci-defaults/check-date-http-cron, packages/eupgrade/Makefile, packages/eupgrade/files/etc/uci-defaults/99-eupgrades-cron, packages/hotplug-initd-services/Makefile, packages/random-numgen/Makefile, packages/random-numgen/files/random-numgen, packages/shared-state-babeld_hosts/Makefile, packages/shared-state-babeld_hosts/files/etc/uci-defaults/shared-state-babeld_hosts-cron, packages/shared-state-bat_hosts/Makefile, packages/shared-state-bat_hosts/files/etc/uci-defaults/shared-state-bat_hosts-cron, packages/shared-state-dnsmasq_hosts/Makefile, packages/shared-state-dnsmasq_hosts/files/etc/uci-defaults/shared-state-dnsmasq_hosts-cron, packages/shared-state-dnsmasq_leases/Makefile, packages/shared-state-dnsmasq_leases/files/etc/uci-defaults/90_dnsmasq-lease-share, packages/shared-state-dnsmasq_servers/Makefile, packages/shared-state-dnsmasq_servers/files/etc/uci-defaults/shared-state-dnsmasq_servers, packages/shared-state-network_nodes/Makefile, packages/shared-state-network_nodes/files/etc/uci-defaults/shared-state-network_nodes-cron, packages/shared-state-nodes_and_links/Makefile, packages/shared-state-nodes_and_links/files/etc/uci-defaults/shared-state-bat_nodes_and_links, packages/shared-state-pirania/Makefile, packages/shared-state-pirania/files/etc/uci-defaults/90-pirania-cron, packages/shared-state/Makefile, packages/shared-state/files/etc/uci-defaults/shared-state-publishers-cron
Fix #800 
Replaces the (other half of) #980 
When https://github.com/openwrt/packages/pull/20728 will be included in openwrt-22.03, the package will need to be removed from lime-packages repository.
=> Adding the random-numgen command and use it for removing usage of $RANDOM

packages/random-numgen/Makefile
Else it's not possible to install on anything but x86
=> random-numgen: set PKGARCH:=all

packages/prometheus-node-exporter-lua-location-latlon/Makefile, packages/prometheus-node-exporter-lua-wifi-params/Makefile, packages/prometheus-node-exporter-lua-wifi-stations-extra/Makefile, packages/prometheus-node-exporter-lua-wifi-survey/Makefile
This remove a compatibility check that search for `iw` and if not found select `iw-full` in prometheus related packages.
The `iw` package is listed since 18.06 https://openwrt.org/packages/index_owrt18_6/start
Instead this check cause a recursive-dependency error, and make the compiler fails.
```
tmp/.config-package.in:60497:error: recursive dependency detected!
tmp/.config-package.in:60497:	symbol PACKAGE_profile-calafou-indoor depends on PACKAGE_iw
tmp/.config-package.in:131539:	symbol PACKAGE_iw is selected by PACKAGE_kmod-cfg80211
tmp/.config-package.in:22741:	symbol PACKAGE_kmod-cfg80211 is selected by PACKAGE_kmod-batman-adv
tmp/.config-package.in:16661:	symbol PACKAGE_kmod-batman-adv is selected by PACKAGE_lime-proto-batadv
tmp/.config-package.in:61230:	symbol …
```
=> remove old iw/iw-full compatibility check

CHANGELOG.md
It would be nice to have a changelog file to know what changes have been made between versions.
This add a 'full' changelog of latest changes up to version v2020.2. 
The details about v2020.1 are still missing, also because, if I'm not mistaken, there seem to be several commits before version v2020.1 not from a fork, but directly merged into master so they are a little harder to detect. Like this one for example https://github.com/libremesh/lime-packages/commit/dacca455d49c78e665343abc5f1df204fa5dde0e (taken from https://github.com/libremesh/lime-packages/commits/2020.1). 
For previous versions, the changelog instead is taken from http://es.wiki.guifi.net/wiki/LibreMesh/Changelog
=> Draft: add CHANGELOG.md

packages/lime-system/files/usr/lib/lua/lime/network.lua
On devices that have only a single lan port, like `D-Link DAP-X1860 A1`, with DSA, the lan port is just called `lan`, not `lan1` as one might expect. This changes a regex `^lan%d+$` to `^lan%d*$`, so that the `lan` interface is correctly recognized and configured.
Instead of just scraping `eth0`, `eth1`, ... from `/sys/class/net/`, the second commit adds scraping of `lan`, `lan1`, `lan2`, ... aswell. Without this, `lanx`-interaces are not configured if they do not appear in the configuration.
=> lime.network.scandevices: fix finding intefaces on dsa devices

packages/shared-state/files/usr/libexec/rpcd/shared-state, packages/shared-state/tests/test_rpcd_shared-state.lua
Shared-state rpcd interface doesn't need to show shared state metadata, only payload data. 
This pull request improves the previous version of the module by exposing only relevant data.
=> removed extra info from shared state

README.md
In #1015, @aparcar created an excellent documentation about using the ImageBuilder for building LibreMesh on OpenWrt 22.03 (not yet supported!!).
In https://github.com/libremesh/lime-packages/pull/1015#issuecomment-1540906636 I suggested a few edits, here I implemented those and many others.
=> readme: expanded instructions on ImageBuilder

packages/shared-state-wifi_links_info/Makefile, packages/shared-state-wifi_links_info/files/usr/bin/shared-state-publish_wifi_links_info, packages/shared-state-wifi_links_info/tests/test_shared-state_wifi_links_info.lua
This pull request addresses the lack of frequency information in wifi links info module 
The module has been tested with two very close tplinks 
and this is the output 
{"primero":{"bleachTTL":30,"data":[{"tx_rate":135000,"dst_mac":"A0:F3:C1:46:28:97","signal":-61,"chains":[-63,-64],"freq":5240,"rx_rate":216000,"src_mac":"a8:40:41:1d:f9:35"},{"tx_rate":135000,"dst_mac":"14:CC:20:DA:4E:AC","signal":-50,"chains":[-50,-62],"freq":5240,"rx_rate":180000,"src_mac":"a8:40:41:1d:f9:35"}],"author":"primero"},"LiMe-da4eaa":{"bleachTTL":30,"data":[{"tx_rate":86700,"dst_mac":"A0:F3:C1:46:28:96","signal":-23,"chains":[-23,-45],"freq":2462,"rx_rate":72200,"src_mac":"14:cc:20:da:4e:ab"},{"tx_rate":270000,"dst_mac":"A0:F3:C1:46:28:97","signal":-49,"chains":[-59,-49],"freq":5240,"rx_rate":300000,"src_mac": …
=> add freq information

packages/shared-state-wifi_links_info/files/usr/bin/shared-state-publish_wifi_links_info, packages/shared-state-wifi_links_info/tests/test_shared-state_wifi_links_info.lua
This pull request is a very small improvement witch adds the interface name for each link in shared state's wifi_information module
=> add wifi interface name in shared state wifi information module 

packages/lime-docs/files/www/docs/lime-example.txt, packages/lime-system/files/etc/config/lime-defaults, tests/test_lime_config_device.lua
Fix #201
Goes against the decisions implemented in #202 and #324
See the discussion on #201 and on this email thread: https://lists.autistici.org/thread/20230815.142621.071b5fc0.en.html#i20230815.142621.071b5fc0
Here, the default distance setting for 5 GHz radios is being increased from 1 km to 10 km.
And the default distance setting for 2.4 GHz from 100 m to 1 km.
=> Default distance setting: increase 10x

packages/safe-upgrade/files/usr/sbin/safe-upgrade
Here is the report https://gitlab.com/librerouter/librerouteros/-/issues/61
I am not exactly sure if this OpenWrt commit should fix it https://github.com/openwrt/openwrt/commit/c29390b0f3ab7d98f96723f1f988b35cbd1637f7 but here I provide an implementation that does not rely on the addition of "big ints" (that are bigger than 2^31).
=> Fix safe-upgrade bootstrap broken since OpenWrt 19.07

.github/workflows/build_2020.yml, CHANGELOG.md, packages/lime-docs/files/www/docs/lime-example.txt, packages/lime-system/files/etc/config/lime-defaults, packages/safe-upgrade/files/usr/sbin/safe-upgrade, packages/shared-state-wifi_links_info/files/usr/bin/shared-state-publish_wifi_links_info, packages/shared-state-wifi_links_info/tests/test_shared-state_wifi_links_info.lua, tests/test_lime_config_device.lua
Changelog updated to 2023/09/01
=> Draft: update CHANGELOG.md

packages/lime-system/files/usr/lib/lua/lime/utils.lua, packages/shared-state-network_nodes/Makefile
Change package maintainer, correct license, plus comment on the code
=> Small cleaning

packages/lime-system/files/usr/lib/lua/lime/proto/lan.lua, packages/lime-system/tests/test_lime_network.lua
Bridge ports are added to the first device section, which may be the wrong one. This changes the behaviour follwing @ilario s [suggestion](https://github.com/libremesh/lime-packages/issues/1060#issuecomment-1767832137). Now, the first device section that has type `bridge` and the name `br-lan` will be used.
After reading the `/bin/config_generate` script in OpenWrt base-files I am confident that there will always be such a device section on first boot.
fixes #1060
=> draft: fix bridge device section confusion

packages/lime-docs/Makefile
This update the PKG_SOURCE_URL and PKG_SOURCE_PROTO of lime-docs.
It seems something is changed from github.com's side: 
- the 'svn' proto is not accepted anymore (see logs) 
- while it is still present an http redirect from `https://github.com/libremesh/lime-web/trunk/docs` to `https://github.com/libremesh/libremesh.github.io/`
The bug is preventing v2023.1-rc2 to be build.
I made sure that this is the only bug that cause a build failure as now the build for v2023.1-rc2 is going on.
<details><summary>Error Details</summary>
<pre>
SHELL= flock /home/antennine/openwrt_build/stable/libremesh_2023.1-rc2-ow22/openwrt_buildroot_22.03.5/tmp/.lime-docs-2023-09-17-1694972618.tar.xz.flock -c '  	 echo "Checking out files from the svn repository..."; mkdir -p …
=> lime-docs: update PKG_SOURCE_URL

packages/lime-system/files/usr/lib/lua/lime/wireless.lua
Fix #1063, where wireless.is5Ghz returns true for the 2GHz radio on TP-LINK TD-W8970.
=> lime.wireless: Fix wireless.is5Ghz

README.md
Building LibreMesh with imagebuilder is difficult. Especially selecting the right packages is not trivial. With these changes and additions I intend to make it easier to build a working image for someone not so familiar with LibreMesh and imagebuilder.
=> Readme.md: improve imagebuilder instructions

README.md
This adds instructions on how to add the `lime-packages` feed to imagebuilder. I forgot to add them in 88d6991377e8b8370f2affa45b3533b530162089.
=> README.md: add info about how to add package feed

packages/wifi-unstuck-wa/files/usr/bin/wifi-unstuck
This updates the module path to its new location, because else `/usr/bin/wifi-unstuck-wa` throws an error and does not work.
=> lime-unstuck-wa: Fix module path

packages/lime-proto-anygw/files/usr/lib/lua/lime/proto/anygw.lua
Make sure anygw is not used for communication with hosts in the same network.
Fixes #1078
=> Set high metric on anygw prefix route

packages/lime-system/files/usr/lib/lua/lime/network.lua
On a mercusys mr70x, lime-config does not work. It throws the following error:
```
network.scandevices.owrt_network_interface_parser found ifname wan
ls: /sys/class/net/wan/lower*: No such file or directory
/usr/lib/lua/lime/network.lua:223: attempt to index field '?' (a nil value)
stack traceback:
/usr/lib/lua/lime/config.lua:221: in function </usr/lib/lua/lime/config.lua:221>
[C]: in function 'foreach'
/usr/lib/lua/lime/network.lua:339: in function 'scandevices'
/usr/lib/lua/lime/network.lua:373: in function </usr/lib/lua/lime/network.lua:364>
[C]: in function 'xpcall'
/usr/lib/lua/lime/config.lua:221: in function 'main'
/usr/bin/lime-config:55: in main chunk
[C]: ?
```
It seems that an interface that is called "wan" does not always have link to a lower interface in /sys/class/net. This …
=> Fix lime-config fail when there is no lower iface

packages/safe-upgrade/files/usr/sbin/safe-upgrade, packages/shared-state-async/Makefile
Fix https://github.com/libremesh/lime-packages/issues/1081 log pollution reported by @pony1k
=> shared-state-async fix log pollution

packages/lime-docs/files/www/docs/lime-example.txt
This adds some documentation on how to set ethernet interfaces for mesh only or clients only.
See for example here: https://github.com/libremesh/network-profiles/tree/master/calafou#lime-community-configuration-3
=> Document how to set ethernet interfaces for mesh only or clients only.

packages/lime-system/files/usr/lib/lua/lime/proto/lan.lua
=> Fix removing ports from br-lan

.github/workflows/build.yml
This prevents all packages from being recompiled when not needed (changes to readme, changelog, other not related files)
=> ci: rebuild packages via sdk only when a package changes

.github/workflows/multi-arch-build.yml, README.md, packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
Add a new packages repository at:
- http://github.com/libremesh/lime-feed/tree/gh-pages/master/packages/$ARCH_PACKAGES
- http://feed.libremesh.org/master/packages/$ARCH_PACKAGES 
That includes packages precompiled by openwrt-sdk for each specific architecture
This is currently required only for the package `shared-state-async` 
After this merge https://github.com/libremesh/lime-packages/pull/1067, imagebuilder builds fail, using the default set of packages, unless you are building for x86_64
update the imagebuilder build guide on `README.md`
update `lime-system/files/etc/uci-defaults/92_add-lime-repos` to use also the new repo
=> ci: add multi-arch-build.yml;

.github/workflows/build_2020.yml
This re-triggers the build via OpenWrt SDK 19.07.10 for packages at branch 2020.4 
This is intended to create the missing repository for packages of libremesh-2020.4 and allow people to install them via opkg.
=> ci: add workflow build_2020.yml

packages/shared-state-bat_hosts/files/usr/lib/lua/bat-hosts.lua, packages/shared-state-bat_hosts/tests/test_bat_hosts.lua
Rpcd get bat hosts call was not working causing lime app UI to fail when trying to retrieve host names. 
This pull request fixes the rpc call. 
the function "bat_hosts.get_bat_hosts_from_shared_state()" was created for testing purposes. 
```bash
ubus call bat-hosts get_bathost '{"mac":"AE:40:41:1C:85:16"}'
{
"status": "ok",
"bathost": {
"iface": "wlan1-mesh_17",
"hostname": "LiMe-8037b1"
}
}
```
=> bat_hosts: fixes rpcd error

.github/workflows/multi-arch-build.yml
update gh-action-sdk from v5 to v7
prevent that entire workflow fail if a single arch fails 
allow to run the workflow manually
disable unnecessary options: default_feed, patches refresh_check, '*.init' files formatting
=> ci: multi-arch-build: enable the build of package index + various fixes

.github/workflows/multi-arch-build.yml
Quick fix for `Error: Action failed with "The process '/usr/bin/git' failed with exit code 1"` caused by the fact that the next job does checkout before the previous one has pushed.
It could be restructured as described here, but for now there is not much need, just do one at a time.
- https://github.com/peaceiris/actions-gh-pages/issues/608#issuecomment-834186136
- How to share matrix between jobs https://github.com/orgs/community/discussions/26284#discussioncomment-3251198
=> ci: multi-arch-build: run one job at a time

.github/workflows/multi-arch-build.yml, README.md, packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
I apologize for bothering again on this topic, but compiling via imagebuilder once again turns out to be broken.
I did not calculate that a subsequent compilation from the build.yml workflow would delete the subdirectory previously created by the multi-arch-build.yml workflow (e.g. now missing https://github.com/libremesh/lime-feed/tree/gh-pages/master/packages).
This fixes it, telling the multi-arch-build.yml workflow to use a different path for output packages to avoid overwriting.
This updates also `packages/lime-system/files/etc/uci-defaults/92_add-lime-repos` and `README.md` accordingly.
This also removes the feeds added by default by buildroot for each feed declared in feeds.conf and resulting in a known opkg error such as the one below:
```
root@ninux-598775:~# opkg update
[...] …
```
=> ci: multi-arch-build: use a different output path

packages/shared-state-async/files/usr/libexec/rpcd/shared-state-async, packages/shared-state-async/tests/test_rpcd_shared-state-async.lua, packages/shared-state/files/usr/libexec/rpcd/shared-state, packages/shared-state/tests/test_rpcd_shared-state.lua
current implementations of rpcd for shared-state are inconsistent this new implementation adds a consistent format across the three implementations (shared-state, shared-state-async, shared-state-multiwriter ) 
In every case calls to shared state get or sync will return a json object wit this format 
```JSON 
{"data":{},"error":0}
```
Also this new implementation for shared-state-async uses a shell script to simplify the implementation 
ubus -S call shared-state-async get '{"data_type": "bat-hosts"}'
```JSON 
{
"data": {
"02:29:0f:a5:1e:d1": "LiMe_a51ed1_eth1_2_29",
"02:58:47:a5:1e:d1": "LiMe_a51ed1_wlan0_mesh_29",
"02:95:39:a5:1e:d1": "LiMe_a51ed1_eth0_29",
"02:ab:46:a5:1e:d1": "LiMe_a51ed1_wlan1_mesh_29",
"02:bb:ed:a5:1e:d1": "LiMe_a51ed1_eth1_29",
"02:cc:4e:a5:1e:d1": …
```
=> Adds shared-state rpcd data,error output format and shared-state-async rpcd reimplementation 

packages/shared-state-async/files/usr/libexec/rpcd/shared-state-async
This pull request enables rpcd publisher call, so a publish followed by a sync deliver accurate and updated data. 
Node A should rpcd call to Node B publish and then 
Node A should call its own rpcd sync using its datatype and the IP of node B
Bat hosts publisher name has to be updated before closing this pull request
=> shared-state-async: add publisher call interface

packages/lime-docs/files/www/docs/lime-example.txt
In the lime-example.txt file, the static configuration of an IP was shown with a line configuring the gateway for that interface.
Here I just added a comment for stating that the gateway configuration can be skipped if no default route is needed on that interface.
=> lime-example: specify that the gateway line in the static proto is optional

README.md
I used the ImageBuilder for building the images for the [canodrom.barcelona/simple network profile](https://github.com/libremesh/network-profiles/tree/master/canodrom.barcelona/simple/).
It was enough to add the network-profiles repository and to add `profile-canodrom.barcelona-simple` to the packages to be installed.
=> readme: added network-profiles repository to ImageBuilder instructions

packages/bmx7-auto-gw-bw-mode/files/usr/sbin/bmx7-auto-bw-test, packages/check-date-http/Makefile, packages/check-date-http/files/etc/uci-defaults/check-date-http-cron, packages/eupgrade/Makefile, packages/eupgrade/files/etc/uci-defaults/99-eupgrades-cron, packages/hotplug-initd-services/Makefile, packages/lime-app/files/etc/uci-defaults/shared-state-reference_state_nodes_info_cron, packages/lime-app/files/etc/uci-defaults/shared-state-reference_state_wifi_links_info_cron, packages/shared-state-async/files/etc/uci-defaults/shared-state-net_stats-cron, packages/shared-state-async/files/etc/uci-defaults/shared-state-publish-all-cron, packages/shared-state-babel_links_info/Makefile, packages/shared-state-babeld_hosts/Makefile, packages/shared-state-babeld_hosts/files/etc/uci-defaults/shared-state-babeld_hosts-cron, packages/shared-state-dnsmasq_hosts/Makefile, packages/shared-state-dnsmasq_hosts/files/etc/uci-defaults/shared-state-dnsmasq_hosts-cron, packages/shared-state-dnsmasq_leases/Makefile, packages/shared-state-dnsmasq_leases/files/etc/uci-defaults/90_dnsmasq-lease-share, packages/shared-state-dnsmasq_servers/Makefile, packages/shared-state-dnsmasq_servers/files/etc/uci-defaults/shared-state-dnsmasq_servers, packages/shared-state-network_nodes/Makefile, packages/shared-state-network_nodes/files/etc/uci-defaults/shared-state-network_nodes-cron, packages/shared-state-node_info/files/etc/uci-defaults/shared-state_node_info_cron, packages/shared-state-nodes_and_links/Makefile, packages/shared-state-nodes_and_links/files/etc/uci-defaults/shared-state-bat_nodes_and_links, packages/shared-state-pirania/Makefile, packages/shared-state-pirania/files/etc/uci-defaults/90-pirania-cron, packages/shared-state-wifi_links_info/files/etc/uci-defaults/shared-state_wifi_links_info, packages/shared-state/Makefile, packages/shared-state/files/etc/uci-defaults/shared-state-publishers-cron, packages/shared-state/files/usr/bin/shared-state-get_candidates_neigh
The random-numgen package was created in #991 as in OpenWrt 21 BusyBox did not have $RANDOM enabled by default (so it was not present in the official ImageBuilder), see #800.
But since OpenWrt 22 it is present by default, see https://github.com/openwrt/packages/pull/20728 so there is no need to use it.
Maybe we can keep the random-numgen package for a few more years and then delete it.
This commit should be picked also in the 2024.1 branch.
Fix #1075
=> Stop using random-numgen, not needed in recent OpenWrt

packages/lime-system/files/usr/lib/lua/lime/network.lua
Initially proposed in this comment: https://github.com/libremesh/lime-packages/pull/1080#issuecomment-2351774330
On DSA devices, the "wan" interface could be named just "wan", without having any lower interface.
This ensures that it gets configured by the protocols even if it has no lower interface.
@pony1k @G10h4ck do you think that the same will be needed for LAN?
=> Ensure that wan interface gets configured on DSA devices, where wan could be the name of the interface

.github/workflows/build.yml
this is intended to postpone #1139 while restoring the automatic build of packages
=> fix: ci build packages failed

packages/lime-app/Makefile
That typo was introduced in January 2019 with this commit https://github.com/libremesh/lime-packages/commit/8fe8d05b3ad126d78f5615d3c8abf74c3e446949 part of https://github.com/libremesh/lime-packages/pull/453
It causes this warning and error messages when building LibreMesh using the [Buildroot method](https://libremesh.org/development.html#compiling_libremesh_from_source_code):
```
WARNING: Makefile 'package/feeds/libremesh/lime-app/Makefile' has a dependency on 'ubus-lime-grondrouting', which does not exist
* pkg_hash_check_unresolved: cannot find dependency ubus-lime-grondrouting for lime-app
```
=> fixed typo ubus-lime-groundrouting in lime-app's Makefile

packages/shared-state-async/README.adoc
This pull request is to address issue #492 and also to help development around shared state. 
Please feel free to make suggestions and even suggest full rewrite of the doc. 
It is a really interesting toppic.
=> New full documentation for shared-state

.github/workflows/multi-arch-build.yml, packages/ubus-lime-groundrouting/Makefile
fix typo from #1141 also in package ubus-lime-groundrouting 
copy fix from #1140 also in job multi-arch-build.yml
=> fix: typo of ubus-lime-groundrouting; fix multi-arch-build

packages/lime-report/files/lime-report.sh
`iw phy` includes some useful information like the supported interfaces' combinations.
For example, for a TP-Link Archer A7 v5:
```
valid interface combinations:
* #{ managed } <= 2048, #{ AP, mesh point } <= 8, #{ P2P-client, P2P-GO } <= 1, #{ IBSS } <= 1,
total <= 2048, #channels <= 1, STA/AP BI must match, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz }
```
And what is interesting for us is that there can be maximum 8 AP or mesh interfaces on each radio.
=> Adding "iw phy" to lime-report

packages/ubus-lime-utils/files/usr/lib/lua/lime/node_status.lua
Fix https://github.com/libremesh/lime-packages/issues/1137 parsing the output of the "ip" command shipped with Busybox (default OpenWrt option)
With this fix, it is no longer necessary to include the ip-tiny package, which has a size of approximately 126 KB depending on the platform. On small hardware platforms where storage is limited, every byte counts.
=> Fix get node status to work with busybox ip command

packages/hotplug-initd-services/files/usr/bin/hotplug-initd-observer
Fix #1064 (see also #1068)
Please, @LaneaLucy or @pony1k, can you test if this fixes?
Unexpectedly, running a similar code on my laptop with Lua 5.4.7 does not result in an error. Maybe it is related to the older versions of Lua?
=> hotplug-initd-observer: Avoid format error when evData.service is empty

packages/ubus-lime-utils/files/etc/udhcpc.user.d/50-client-wwan-watchping
The first and the third commits fix #956 
I considered that the usage of watchping is not a real dependency of this package (this package does things even if watchping is not doing its things). So, rather than adding the dependency, I added a check for the existence of watchping (first commit).
The second commit is fixing a bug undetected since its introduction in https://github.com/libremesh/lime-packages/commit/400ac95448a1f1d5a83496488e40c302cde766f0 within #890
The third commit is checking if the `client-wwan` interface exists before running ip on it.
This could also be merged in the 2024.1 branch for the upcoming release.
=> Fixes on ubus-lime-utils

packages/lime-system/files/usr/lib/lua/lime/network.lua
On a YouHua WR1200JS I could observe two error messages from `ls` when running `lime-config`:
```
...
network.scandevices.owrt_network_interface_parser found ifname lo
network.scandevices.owrt_network_interface_parser found ifname br-lan
network.scandevices.owrt_network_interface_parser found ifname wan
ls: /sys/class/net/wan/lower*: No such file or directory
network.scandevices.dev_parser found WAN port wan
network.scandevices.owrt_network_interface_parser found ifname wan
ls: /sys/class/net/wan/lower*: No such file or directory
network.scandevices.dev_parser found WAN port wan
network.scandevices.owrt_device_parser found base interface not_found and derived device br-lan
network.scandevices.dev_parser got nil device
...
```
This happens as `wan` on this router [is the name of the …
=> network._get_lower do not cause "ls" error when there is no lower

packages/lime-system/files/usr/lib/lua/lime/network.lua, packages/lime-system/files/usr/lib/lua/lime/proto/lan.lua, packages/lime-system/files/usr/lib/lua/lime/utils.lua
- Scrape configurable network devices from /etc/board.json.
- Avoid configuration on DSA conduit devices.
- Allow device specific configuration for network devices with
arbitrary names. This is more intuitive from a users perpective. Before, devices whose names don't match certain patterns were ignored. This could be helpful for network devices with unforseen names.
- Remove 'nobridge' tag, as this seems no longer be needed.
- Add optional parameter 'port' to utils.is_dsa().
- Add 'dsa' tag for DSA user ports. This could be used to fi_x #1121 like suggested by @ilario in [this comment](https://github.com/libremesh/lime-packages/issues/1121#issuecomment-2525078108).
fixes #1132
=> Scrape device names from board.json

packages/lime-docs/files/www/docs/lime-example.txt, packages/lime-hwd-watchcat/Makefile, packages/lime-hwd-watchcat/files/usr/lib/lua/lime/hwd/watchcat.lua
This implementation covers the suggestion made [here](https://github.com/libremesh/lime-packages/issues/1177). The code configures watchcat every time `lime-config` is run. 
For the moment `deferrable-reboot` has not been removed.
Please review and let me know if you think it is safe to remove `deferrable-reboot` entirely, or if further adjustments are needed.
=> Replacing deferrable reboot with watchcat

packages/lime-system/files/etc/uci-defaults/92_add-lime-repos
There was a typo in `distfeeds.conf`, and the previous syntax worked only on openwrt SNAPSHOT
=> lime-system: fix typos in 92_add-lime-repos
